In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
import string
import nltk
nltk.download ('stopwords')
from nltk.corpus import stopwords 
from nltk.tokenize import WordPunctTokenizer

from config import MAPBOX_API_KEY
import plotly
import plotly.offline as py
import plotly.graph_objs as go
import plotly.express as px

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/MariloyHJimenez/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
import warnings
warnings.filterwarnings('ignore')

# Importing Clean Data

In [3]:
file_path = "Resources/Final_philadelphia_reviews.csv"

phillies_df = pd.read_csv(file_path)
phillies_df["business_id"].count()

10000

In [4]:
yelp_reviews_df = phillies_df[['review_id', 'user_id', 'business_id', 'text', 
                               'stars_business', 'review_count']]

In [5]:
#restaurants_df = pd.read_csv('Resources/Philadelphia_businesses.csv')
restaurants_df = pd.read_csv("Resources/Philly_NearRestaurants.csv")
#Check Null values in restaurantes
restaurants_df.rename (columns={'ID':'Business_Id'}, inplace=True)
restaurants_df['Business_Id'].count()

50

In [6]:
restaurants_df.head(10)

,name,latitude,longitude,stars_business,categories,review_count,Business_Id
0,Saad's Halal Restaurant,39.954963,-75.211851,4.5,"Halal, Middle Eastern, Restaurants, Food, Indi...",702,6_LnAQQ0-mml8YgpfRjGuA
1,Mood Cafe,39.948664,-75.215832,4.5,"Cafes, Pakistani, Juice Bars & Smoothies, Rest...",458,U30ggGzFpXvc2NZYwOW3qg
2,48th Street Grille,39.953137,-75.218661,4.5,"Internet Cafes, Restaurants, Food, Seafood, Am...",275,KYPhGJIibu_7ePIX4HNs6A
3,Cucina Zapata,39.954289,-75.185538,4.5,"Thai, Food Stands, Restaurants, Mexican",248,B-DiQpcSTJ7oMMnwzbAGTQ
4,Fu-Wah Mini Market,39.948292,-75.217014,4.5,"Grocery, Food, Convenience Stores, Restaurants...",247,Biidj3QszVuVO0Q85g5NPw
5,Dottie's Donuts,39.948345,-75.213656,4.5,"Restaurants, Food, Vegan, Cafes, Donuts",206,A3Qt87F7ZaAwCW4CyyB1Fw
6,Tacos Don Memo,39.951988,-75.199123,4.5,"Food Trucks, Specialty Food, Food, Restaurants...",200,eXKblEHP3YJYU1Awz08hVw
7,Lee's Deli,39.948441,-75.217116,4.5,"Sandwiches, Burgers, Delis, Restaurants, Local...",175,KHe6HAqmyioITwTvg9Bbcg
8,White Dog Cafe,39.953558,-75.192905,4.0,"Cocktail Bars, Gluten-Free, Bars, Diners, Vege...",1301,ZKPrXH_GNW_AtZ31tP3NmA
9,Sabrina's Café,39.959879,-75.190681,4.0,"Breakfast & Brunch, Restaurants, Vegetarian, A...",833,6ewV-e7-39oqYUq3yZuIyw

In [7]:
# Fill with empty string the NaN reviews
yelp_reviews_df.dropna(inplace=True)
yelp_reviews_df[['text']] = yelp_reviews_df[['text']].fillna('')
yelp_reviews_df.head()

,review_id,user_id,business_id,text,stars_business,review_count
1,sFQrhTbTah0o2kU_Pi2D0Q,Tu4ATXLhy8kRTjpQCnl2pA,ytynqOUb3hjKeJfRj5Tshw,One;of;my;favorite;places;to;go;to;in;Philly;;...,4.5,5721
2,kqn1uP3LRVjVDUD44ZSu1A,vRNb2IaGlsZRA_wUf3Ov8w,ytynqOUb3hjKeJfRj5Tshw,This might be a bit unfair to have a single re...,4.5,5721
3,qMsTe9QznpNQk1AKbYLp-w,29K-usmZfVDeIaQ85EG54A,ytynqOUb3hjKeJfRj5Tshw,Alright; I remember the first time I went to t...,4.5,5721
4,nmMIRBNONIICe7CFHnfadQ,1jE--VcTddwXGampD23JCg,ytynqOUb3hjKeJfRj5Tshw,It's;an;experience;;to;say;the;least!;;Not;as;...,4.5,5721
6,dXVhYlcX9X9kqVI16AoBHg,lavyYLh68LxIBhJdIE5f_g,ytynqOUb3hjKeJfRj5Tshw,fresh;seafood;and;produce.;fresh;breads;;chees...,4.5,5721

In [8]:
yelp_reviews_df.count()

review_id         8303
user_id           8303
business_id       8303
text              8303
stars_business    8303
review_count      8303
dtype: int64

In [9]:
yelp_reviews_df.rename (columns={'review_id': 'Review_ID', 'user_id' :'User_Id', 
                        'business_id':'Business_Id', 'text':'Reviews', 
                'stars_business': 'Rating', 'review_count' :'Review_count'}, inplace=True)

# Begin the reviews cleaning, selecting only stars and text

In [10]:
yelp_reviews_df["Reviews"]

1       One;of;my;favorite;places;to;go;to;in;Philly;;...
2       This might be a bit unfair to have a single re...
3       Alright; I remember the first time I went to t...
4       It's;an;experience;;to;say;the;least!;;Not;as;...
6       fresh;seafood;and;produce.;fresh;breads;;chees...
                              ...
9993    Let down. I was in a hurry to catch my next fl...
9994    I;dont;give;one;star;reviews;but;they;earned;i...
9995    I;would;give;negative;stars;if;I;could.;Chewy;...
9997    So if you want a cheesesteak at PHL airport; t...
9999    Have;to;say;Geno's;is;a;great;place;to;get;a;c...
Name: Reviews, Length: 8303, dtype: object

In [11]:
#Select only stars and text
reviews_df = yelp_reviews_df[['Business_Id', 'User_Id', 'Rating', 'Reviews']]
reviews_df["Reviews"] = yelp_reviews_df["Reviews"].str.replace(";", " ")
reviews_df["Reviews"]

1       One of my favorite places to go to in Philly  ...
2       This might be a bit unfair to have a single re...
3       Alright  I remember the first time I went to t...
4       It's an experience  to say the least!  Not as ...
6       fresh seafood and produce. fresh breads  chees...
                              ...
9993    Let down. I was in a hurry to catch my next fl...
9994    I dont give one star reviews but they earned i...
9995    I would give negative stars if I could. Chewy ...
9997    So if you want a cheesesteak at PHL airport  t...
9999    Have to say Geno's is a great place to get a c...
Name: Reviews, Length: 8303, dtype: object

In [12]:
def text_process(mess):
    """
    Takes in a string of text, then performs the following:
    1. Remove all punctuation
    2. Remove all stopwords
    3. Returns a list of the cleaned text
    """
    print (mess)
    
   # Check characters to see if they are in punctuation          
    nopunc = [char for char in mess if char not in string.punctuation]

    # Join t('stop_word(he characters again to form the string.
    nopunc = ''.join(nopunc)
    
    # Now just remove any stopwords
    return " ".join([word for word in nopunc.split() if word.lower() not in stop])

In [13]:
from nltk.corpus import stopwords
stop = []

for word in stopwords.words('english'):
    s = [char for char in word if char not in string.punctuation]
    stop.append(''.join(s))

In [14]:
reviews_df['Reviews'] = reviews_df['Reviews'].apply(text_process)

One of my favorite places to go to in Philly  and I take every one of my visiting friends here! This place has a lot of yummy stores and awesome stores ( recommended: the grilled cheese place at Meltkraft Grilled Cheese  the donuts at Beilers  4 Seasons Juice Bar  Muellar's Chocolate Co.  icecream from Bassetts  and local honey from Bee Natural). I love coming here  and even though it can get really crowded during lunch hours on the weekends  it's still worth it.
This might be a bit unfair to have a single review  as each stall has very different fare with a variety of qualities. It can definitely be considered food heaven  but on the contrary on a Saturday morning can be Philadelphia hell. The produce at Iovines is very good and fresh  and very very reasonably priced. It can be hectic but the lines go extremely quickly. The rest of the market tends to have very long lines - but the lines can be an indication of the HAVE TO eat. The Original Turkeys turkey sandwhich with cranberry and stuffing. The Cannolis at Termini Bros (best I've ever had)  Becks Cajun Hurricane Sandwhich  Anything at Beilers  but especially their Donuts and their pecan cinnamon rolls  The Reuban or Rachel from Hershels  DiNicks Roast Pork  Dienner's chicken  but most importantly Millers Twist! Its definitely an experience you dont want to miss as a tourist  and if your a local you already go there regularly!
Alright  I remember the first time I went to the reading terminal and being overwhelmed by the barrage of smells  noise  and people walking back and forth experiencing this massive food/dining market all at the same time. In order to save you  my readers from doing the same research I did to find the 'best of the best '   Here is a list of my suggestions (you can view my personal reviews as needed)  1. Any pretzels from Miller's twist - $2.5 (soooo delicious) 2. Roast pork sandwich from DiNic's - $8-10 (very intense provolone taste  voted best in many food magazines) 3. Gumbo at Beck's Cajun Cafe - $10 (lots of flavors  big bowel  a little bit salty)  Additional things to try (from other viewers) 1. Beiler's doughnuts 2. Roast duck noodle platter at Sang Kee Peking Duck House 3. Apple dumplings at Dutch Eating Place  If you want to explore  I'd recommend going aisle by aisle first to see what's available before you settle down. Here's my recs:  Step 1 - walk and explore Step 2 - choose where you want food(s) from Step 3 - find a table (hardest part) Step 4 - have one person sit there and then get food. Step 5 - don't forget to get napkins and utensils Step 6 - eat and repeat
It's an experience  to say the least!  Not as many good vegan options since Basic 4 left  but it is still a neat place and a good place to get breads  jams  produce  and other delicious things.
fresh seafood and produce. fresh breads  cheese wheels spices and great restaurants for lunch
Reading terminal is always crowded. The food is fresh  the people are from different places. The environment is awesome.
Go hungry and early!  Can eat anywhere in the market and get a great meal.  Doesn't matter which spot you pick  I've lived in Philly for 6 years and haven't been able to go to every single spot here.  When I last checked I have been to about 75% of all the stands.  It will satisfy any and all cravings you have.  Just follow your nose!
This is a great spot for fresh local foods  candies to taste there or buy produce and meats to take home. Great farm to table market place! I wish I lived closer so I could have brought some of them home! I had a Dinics sandwich and some great candies from local companies.
In one word: Dry.  In three words: Dry and flavorless.  Preferred Geno's  but only because his cheez whiz makes it less dry.  My comparison review of Genos v. Pats: Despite their poor reviews on Yelp for being over priced  less than spectacular  and staffed by greasy men with the unique streak of arrogance borne of notoriety  we felt that experiencing the origins of the 'steak would be more rewarding than tracking down steakeries more highly regarded by the on-line community.   So off to South Philly we ventured. We had been warned by other steak hunters that the area inhabited by the legendary steakeries was dilapidated and dangerous- so we were happily surprised to find them located in a vibrant community reminiscent of the San Francisco Mission (except with a lot less Latinos and a lot more Italians.)   Arriving unmolested  we broke into teams to procure steaks from each of the shops (without out having to stand in both the long winding lines sequentially.) Our team went to Geno's  while Priscilla  Tammy and Sam went to Pat's to pick up our steaks.  Geno's was interestingly decorated in photo's of the owner and his son posing with scantily-clad  skanky looking women and various celebs  as well as over the top pro-American propaganda and anti-immigrant rhetoric.   I was warned by a woman in line that I must order our steaks with the whiz. Apparently it caused quite an uproar when John Kerry failed to order the traditional \South Philly \" from Geno's- note that Pat's doesn't serve the whiz  so apparently the style only represents the north corner of the intersection  rather than all of South Philly.  When I returned to our seats  team 2 had already procured our steaks from Pats. Apparently some confusion had occurred during ordering  and we now had in our possession 7 steaks- 4 from Pats  and 3 from Genos.   Both steaks were pretty basic- thin strips of steak with onions on bland French rolls  Pat's came with the traditional Provolone and Geno's with the aforementioned Cheese Whiz.  I started by eating one half of a Pat's steak. It was decent  but uninspiring. Several members of the expedition complained that Pat's Steaks were too dry. While not overly moist  I didn't share their concern  however the flavor was lacking in my opinion. Pat's Steaks were very bland in flavor  reminding me of my own creations before I got down with Montreal seasoning and fresh garlic. The cheese was also lacking in flavor.   Next  I moved onto a Geno's steak  with the Whiz. I was intrigued by the flavor and consistency of the Whiz  the steak was juicier than Pat's and the Whiz and grease mixed into thin cheese-gravy that soaked the otherwise bland roll. The meat was similarly bland to that of Pat's  but the flavor of the Whiz compensated for the most part.   I ended up consuming about 2.5-3 steaks in various portions in the sitting  as a excess had been ordered and various members of the expedition were unable to complete their missions  so I feel that I am qualified to end the age old debate as to who makes the best Cheese Steak:  Consensus amongst the group was that Geno's made the better steak of the two  but Geno's lost points due to the quasi-racist vibe  and at least 1 member of the expedition didn't care much for the Whiz. If we had spent more than a single night in Philly  we would have undoubtedly searched for less famous  but more delectable competition  but unfortunately we left the City of Brotherly love disappointed by the over-hyped  over-rated 'steaks.    Mike's Ratings: (On a scale from 1-5  5 being perfect and 1 being inedible.)   Cheese Steak Shop: 4.5-5 (Great tasting  but pretty expensive. I require a 15' to fully satisfy my hunger) Geno's: 3-3.5 (Tasty  also too damn expensive)  Pat's: 2.5-3 (Very bland  I can do better at home.)   Vanessa's Ratings: Cheese Steak Shop: 5 (\"Yummy!\") Geno's: 3.5 (\"I wouldn't go out of my way to stand in that line & he's racist.\") Pat's: 2 (\"It was too dry.\")"
So basically because it's famous  they over charge for their overly greasy and mediocre cheesesteaks  but you're still going to go here. The guy taking my order reminded me of the Soup Nazi and I was scared to mess up my order. A cheesesteak is $10  fries $4.50. Crazy right? The sizes are smaller than others I've had  extremely greasy  under seasoned and extremely overrated. As fast as I got my cheesesteak it wasn't even hot  what?! Jim's and Ishkabibble's on South St are way better... don't waste your time or money.
You. Are. Kidding. This is the worst cheese steak I ever had! Stale bread  grizzled meat. Not even close to good. The Emperor's New Clothes. A joke and a ripoff. Geno's is no better  by the way. These are gimmicks.  Go to Sheetz.
I can't really compare Pat's and Geno's since I didn't have to taste Geno's cheesteaks  but Pat's was quite good!  There were so many flavor combination available but I stuck to \Steak Whiz Wit-Out\"(no onions just cheez whiz)! Make sure you do your order right  be quick and have cash.  @ lunch-be prepared to find parking and/or eat while standing. Don't you worry...it's all worth it.  I stopped @ Pat's hours before my flight back to Cali and wished I ordered another one for my plane ride back home."
Finally a real Philly Cheese Steak. I got a whiz wit. The bread was soft  the meat was  well meaty  and the cheese was whizzy. Best cheese steak I ever had.
Claim to be the inventors of the Philly Cheesesteak. We literally walked 2.5 miles to get here (our own decision)  so we were starving when we got there. Don't worry when you see the long line  they serve about 15 people a minute (no joke). I asked for American cheese on mine  but I'm pretty sure you get cheese wiz no matter what. Also watch out for the service: I'm pretty sure the rudeness is part of the act  but I was very taken aback when the guy yelled at me WHILE I was ordering. Definitely be prepared when you step up to order.  All of that being said  the food was great! I got the cheesesteak with onions and covered it with ketchup. Delicious! And definitely get the fries!! Literally the best fries I've ever had. If you're looking for fast food  this is a great choice. Minus one star only for the service.
Meh. Not too impressed.So I had to do the Pat's vs Geno's taste test for myself after seeing it on The Travel Channel.Lets start with the building.....it looks like Snooki & Jwoww live there.VERY GAUDY.If they put the effort they put into making the outside of the building gaudy into their Cheesesteaks then maybe their Cheesesteaks would be really good.I ordered a Cheesesteak add Provolone American and onions.The bread was really chewy compared to Pat's and the meat was very dry.The meat to bread ratio just wasn't right either there was just too much dry  chewy bread & too little meat.At one point while I was chewing a bite I felt like I had cotton mouth.(Beleive me that's not a good feeling.) There was definitely less meat and cheese on my Geno's cheesesteak & overall the sandwich was just bigger at Pat's. I know that there are waaay better cheesesteak places than these 2 in Philly because we asked some locals but I had to do the \touristy taste test \"thing for myself.The results are in  and the winner is..........Pat's. Next time I come to Philly I won't be coming to either one of these just because I wanna go try other places but if you absolutely had to choose from these 2 then it's definitely Pat's hands down."
Kind of disappointed that after waiting 20+ mins in line in the freezing cold weather  the cheesesteak was not worth it. Wanted to try an authentic philly cheesesteak whilst there  so upon looking at the piling long lines of people waiting to get their hands on geno's Philly cheesesteak we joined the line as well  thinking long lines = Awesome food. Boy  were we wrong. Ordered 1 philly  1 mushroom philly. Taste was bland  no flavor  bread as mentioned in numerous other reviews was chewy and i second that 100%. The meat seemed not up to the standards of philly steaks. And to add a cherry on top  the old lady at the cash register tried to short change me. Delassandros was way way way way way better when I had their cheesesteaks before.  So as of now  number 1 cheesesteak is still mitchels in OCMD  number 2 delassandros  philly. Number 3 ??
Yeah  there's a rivalry with Pat's. Yeah  they have neon. Yeah  their bread is fresher. However  I think Geno's is average. With so many options in the city  Geno's is popular because that's where the tourists go. Try Chinks or Delassandros  much better experience. If you want the typical Philly cheese steak experience  go to Geno's. If you want a better steak  go somewhere else.
Well  here is another three star rating and this is why .   I am a native Californian so I can picture it already. \EY  Waddayanow about steaks?\" Well  l may not know cheesesteaks  but I know what I like.   I did like the sandwich  but it wasn't what I thought it would be. It had good flavor  and I loved the onions. I ordered it \"wizz  wit\" and I was surprised how FAST they get things done. I also got the cheese fries and a drink. All in all it was around $15 (!) and I ate it right there on the benches. Yes  it was cold with the wind blowing.   The best way I can describe it is to draw a parallel observation with another LA landmark that people rave and fawn over. King Taco. Sure  they make good food. Sure they serve tons of customers every night and are rather well known. Sure they make GREAT late night stops. However  late night munchies are not really the best way to judge foodstuffs. Perhaps being soaked in booze from late night carousing adds to the overall experience. There is NOTHING wrong with that. Just in the same way I like King Taco  I liked Geno's.  I however  have had better cheesesteaks. So far  the best cheesesteak I have had in the US was at Moochie's in Salt Lake City. It is not blasphemy  and it in no way takes Geno's down for what it is. A pioneer in the field of cheeseteaks with a history only perhaps one other restaurant can rival. That rivalry I am sure also adds to the legend.   Still  3 stars for the food. -Subject to change based on intoxication-"
Take a picture there then leave. If you're unbelievably famished  then order the cheese fries.
Geno's suffers from being over exposed and hyped  but really from a purely impartial standpoint  their steaks are above average.  I think the steak itself is a 3.5 star product  but their hot sauce earns a star just by itself.  It's one of the best (and spiciest restaurant hot sauces I've encountered).  Give it a shot  the hot sauce makes the steak twice as good.  Be forewarned to add it sparingly -- it is hella hot.  If you think of hot sauces on a scale of 1 to 10  where Frank's Red Hot is a 1.5 and Tabasco is a 3.  The Geno's hot sauce is a 7.
Worst steak I've had in Philly. Cannot understand why anyone likes this place. The folks behind the counter are unfriendly at best and down right rude under normal conditions.  Food-wise  the steak was very bland. No salt/pepper. Cheese was like plastic. Way over priced for soggy  bland food. A real let down.  I took my wife here as she was new to Philly as a tourist treat and we were sorely disappointed. The best steak I've had thus far is the unknown joint up on Somerset and Broad  \Broad Street Steaks\". So good you'll hurt yourself!  Leave this guy and his rude ways and get a real steak some place else."
Great food  slightly over priced. Nacho mamas are great and so is the lobster.
Being a Mexican that was born and raised in California has left me with a bit of a snobby complex when it comes to Mexican food. El Vez first and foremost  looks inviting and fun. Every time I walked by you would see these massive bowls of guacamole and it seemed like everyone was drinking margaritas. My mom and I tried to get a table but the wait was 2 hours and reservations were booked all the way into the next week. I decided next time I was in philly  I would call ahead and book a table. When I finally did eat there  I wasn't disappointed. The owner really put in the effort to keep the place authentic. The food was a little more gourmet than your average CA street taco man  but it was still delicious. The margaritas were strong and delicious and the guac was yummy too. Overall  a great experience.
We were looking for a brunch spot  our first choice had to long of a wait so we tried this place. We never had Mexican themed brunch before  it was delicious! The service was good (not great but it met the need). It was not a long wait between ordering and getting our food. I would visit here again!
We went here while on vacation in Philly last week. It was my favorite and most memorable meal of the trip! We had the original guacamole and it was amazing. I also had a delicious margarita. For dinner my boyfriend ordered chicken enchiladas which were really great  and i ordered the carne asada  which was the best thing of the whole meal. Michelle was our server and was really sweet! My boyfriend forgot his shopping bag there and they held onto it for us until we could come back the next day (in nyc where we live  that bag would have been gone!!!)
I say this is the best/most creative Mexican food in Philly. For a college student or (poor) young professional  this is definitely a treat yo'self dining experience. But it's SO worth it!  Advice:  1. This is my go-to margarita place  so definitely start with one! They're all wonderful  depending on your taste  and made with a generous amount of alcohol. I've had the original one as well as the pineapple margarita and both were delicious.  2.Share some guac with your friends! De la hoya is my favorite! So fresh  and the chips are homemade and perfectly crispy. 3. Two Words: MACHO NACHOS. These are prepared in a large  skillet-type dish  so EVERY chip is nicely covered with toppings. Great for sharing between 3 or 4 people if you're all getting entrees as well.  4. Try the Crispy Mahi Tacos for your meal! Beautiful presentation  fresh fish  and a complementary sauce that's the perfect combination of tang and spice.  5. If you have room  order the corn on the cob as a side. This comes covered in cheese and savory spices.   I've never had room for dessert at El Vez! Every time I leave  I'm happily full and already thinking about the next time I can go back!
Overall a great menu  great atmosphere and great service. Really enjoyed eating here.   Food: we ordered the Cesar Chavez guacamole which had Oaxaca cheese and pasila balsamic sauce as an appetizer. The guacamole had very unique flavors and the presentation was beautiful. For entree  I tried the chicken tacos which were deliciously seasoned and paired with a juicy salsa and a slice of avocado. The plate presentation was really beautiful as well.   Atmosphere: the decor of the restaurant was really unique and beautiful - it's a very colorful restaurant. It's a loud environment since it seems to always be crowded and has a bar so if you are looking for a quiet sit down dinner I wouldn't recommend coming here.   Service: the service was great  our waitress gave us ample time to order and was quick to get the food out to us despite it being crowded.   My one tip is to make a reservation. We hadn't made one and were told it would be an hour and a half wait for 4 people at around 4pm on a Saturday which didn't seem to be a busy time for any other restaurants located near by. We were lucky and only ended up waiting about 20-30 mins and browsed the stores near by. So to be safe  definitely make a reservation if you don't want to wait!
Being from Texas  I enjoy Mexican food and while traveling for work a co-worker found this place and fell in love!  I went twice while I was there and absolutely love the Chicken Tortilla Soup and I'm not a big soup person.  The Macho Nachos are big enough to serve 4 people and are better with Chicken than Beef.  They are famous for their different kinds of guacamole (I never had any but heard they were good).   I had the Blood Orange Margarita and it was pretty good.    The place is a little pricey but is worth it.  Also they were kind enough to give us a call on our cell phone when our table was ready if there was longer than a 30 minute wait.  Kind of sad that I'm not traveling to Philly anymore because I will miss this place.

The Han Dynasty was a great venue for our wedding rehearsal dinner! Their dishes are very authentic Chinese cooking and everything we had tasted great. The menu selection and service were excellent  and Megan helped us create a custom menu to mix authentic Chinese and kosher styles  while also incorporating plenty of items for vegetarian and other dietary restrictions. The restaurant comfortably seated 80+ people in their side area with constant  friendly service the whole night. In spite of some misunderstandings on menu totals and pricing  Megan was very patient and accommodating and helped us sort everything out. At the end of the night  our family and friends loved the food and everyone had a great time.  I highly recommend the Han Dynasty to anyone for great food  service  and events coordinating!
Han Dynasty is one of my favorite restaurants in Philadelphia.  I first found the Manayunk location  and my wife and I ate there several times.  We heard about it from a friend who turned us on to the spicy cucumbers  which are just wonderful.  Eventually I tried the University City location  and it's much more \hip.\"  I really don't care about ambiance  but if you are seeking a more polished/trendy type of place  go to University City over Manayunk.  The food in both places is just incredible.  Han Dynasty serves food in very large  family sized portions.  It's most fun when you are with a bit of a group  so you can order a number of different things  and try them all.  On their \"specials\" menu  they have Spicy Aroma Fish which is just absolutely beyond this world.  SO good.  Another major hit was the dry pot style.  My wife and I are big seafood fans  so we get shrimp as the protein  but you have complete flexibility to pick whichever protein suits your taste.  They have numbers on the menu  1-10  beside each dish.  This is the relative spiciness rating.  It's really hard to describe the type of heat in these Szechuan dishes... it isn't the kind of heat that just burns your mouth.  The heat is very strong  but it's all flavor.    Dry pepper style is another type of preparation that we have tried and loved.  Several reviews mention the Dan Dan noodles... they are wonderful  but they are indeed rather oily.  It's just the nature of this cuisine.  I think the food is wonderfully prepared  one just has to know that chili oil and sesame oil will make the food a bit on the oily side.    Absolute top notch rating for this place.  Love it!"
Couple of notable impressions:  - The first thing that got me was the decor of the place. Chopsticks were made out of red plastic  and the napkin was just paper  not cloth. Water came out in glass cups. The impression was overall a little cheap  which surprised me. On the other hand  the servers did keep water refilled well and tea was presented immediately.  - A lot of the reviews remark that the dishes are very spicy. I was surprised to discover it was pretty tame. The Dan Dan noodles come in at a 6 and it was imperceptible. We got another dish coming in at an 8 which also was hard to notice. Not sure what the explanation might be since I don't consider myself to be especially tolerant  but perhaps I'm more so than I think?  - Service was very fast. I think our food came out within ten minutes. Certainly the Dan Dan noodles were instantaneous.  - Finally  the food itself is delicious. The Dan Dan noodles especially. I also had some kind of dumplings and an entree  I unfortunately can't remember the names  but both were enjoyable as well.  - The bill was a bit pricey. I think they give a lot of food for two  so it's may be justified  just unwanted for two relatively small people. Fortunately  they make taking it home easy if that's something you'd like.  EDIT:  - After visiting a second time with a large group  I discovered they have a very nice seating area for groups (to the right and somewhat below ground). We got a circular table which I really liked for discussion. Definitely would have appreciated a turntable  but no big deal.  - A tip from our server: the spice tends to be the kind that creeps up rather than is entirely overt. Besides water  consuming tea and rice helps to reduce the effect of the spice.
mmmm burgers and milkshakes.   i love that you can sit outside.  i also love that the food is always piping hot and delicious. I love the creamy cheesesauce for the fries. i love that even when the line looks long  the wait is never really that long. i love the reclaimed bowling lanes that have been turned into tables.  i dont love:  hmm. drawing a blank.
Tell Em  Sam! https://www.youtube.com/watch?v=ecc0nbg9m-8
Solid burgers and shakes.    Best fast food-esque burger in Philly  definitely better than five guys.  Only draw back is the price...where it will run you about 15 bucks for a small burger (1 patty)  fries and a shake.  A bit too expensive for casual lunch outside of NY.  The price is even more offensive after you consider a double double animal style with fries and a shake from In & Out Burger in LA is only 8 dollars.
First time at the Shake Shake on a Saturday night at 9:30. It was still bumpin'. The menu is pretty big and written on the wall... It was a little overwhelming as a first timer. I went with a simple vanilla shake and my wife got a 50 50--iced tea lemonade. My friend got a PB shake and fries. You get a buzzer to alert you when your food is ready--great idea! We got our items very quickly  despite it being very busy. There are tables and a counter to sit at. It was very full so we sat at the counter. The fries are really good--so crispy. The shake was also awesome--perfect consistency. Can't wait to go back and have burgers and fries. I like that they have tons of bike racks and planters around the inside.
My first visit to Shake Shack (not just the one in Philly but any Shake Shack anywhere) was a success overall.  The line moved very quickly considering it was dinner time on a Friday night. I wasn't even planning to order anything as I wasn't hungry  but wound up with a bacon cheeseburger and a side of ice cream. Go figure.  The burger was very good though not some blissful nirvana that all the hype would suggest. A better one can be had right across the street at Village Whiskey. The ice cream (which I got carded for LOL) was a beer-nut flavor. It was good  though everyone else said it tasted beery...I didn't notice that  which probably indicates the degree to which my taste buds have been trained to ignore the taste of alcohol. Oops.
What can I say  it's the best fast food burger out there. They cook them perfectly and dress them very well. There's no grease running off of them like disgusting Five Guys or Smashburger. The fries are great too. Considering this place went from a tiny cart in NYC to locations worldwide in about a decade  I'd say they're onto something.
If you are going here  I would definitely recommend the Shack stack burger. A beef burger with a veggie patty as well. The veggie patty consists of mushrooms stuffed with cheese. It is amazing. The fries however  are alright they could use more cheese  and they were a bit salty. My husband got the double stack burger  and that was pretty salty as well.  The shakes are amazing though !
Shake shack is ALWAYS delicious. I don't know who would give shake shack less than 5 stars. The staff is always friendly - every time I have a dog with me  someone brings out a water bowl without even asking - the service is quick  they have beer and wine!!! and the burgers are a revelation. The potato bun alone should win an award. Also  if you haven't had a peanut butter milkshake  you are missing out on life. Lastly... Not that I would ever choose this over the burger  but the buttermilk chicken sandwich is unreal. I tried it once and haven't stopped talking about it  but I can't stray from the original cheeseburger. Village whiskey is right across the street (also amazing) but I would still pick shake shack every. single. time. I'm obsessed.
This was my first visit to Shake Shack. The burger  fries  and shake held up to the hype. I loved the bun which had a hint of sort of sweet Hawaiian taste to it. The only problem with this place is the price.
Came here for lunch with my fiancee and friend  found a small table by the window.  they have a great and varied wine selection.  I got a bubbly and my fiancee got some Italian orange soda.  We got the lamb sausage  potato chips  and crab stuffed peppers as \snacks\" then i got the mozzarella with prosciutto bacon bits sandwich which was delicious and savory while being light and healthy. service was prompt and polite.  rustic  intimate  and cozy wine lounge atmosphere with low to medium noise level.  bathroom door lock and handle are kind of confusing to use at first. would definitely recommend for lunch!"
Tria's employees are very knowledgeable about the selection of beers and wines they offer. This is probably why I look forward to going to Tria. This location has outside seating during the warmer months and is a real treat if you can get a table out there. It always seems to be busy  which is a good thing. I've never had any of the food items at Tria  because the real treat here are the drinks.
both locations deserve 5 stars but my favorite location is in rittenhouse . I love the atmosphere :)   Getting a tria card is well worth the small fee its a great way to keep track of the different wines  beers and cheese.  Sign up for the email lists as well they will keep you in the know of all the happenings going on during the week.   Tria has great staff   fantastic cheeses  wines and beers from all over the world.
Was wandering the streets of Philly and came across this restaurant.  Realizing I hadn't eaten all day I stopped off to grab a sandwich.  I immediately fell in love with the atmosphere and the staff was amazing and friendly.    Sitting alone enjoying the view  a glass of proseco  and my amazing turkey sandwich  the staff checked in and offered light banter.    Very impressed and highly recommend.
My only hesitation to write this review is that it's almost trendy to review Tria  but the biz shouldn't be punished for it...   My mistake is I passed by this place so many times thinking I should stop in  especially since it's packed  but figured the alcohol would be overpriced and food would be an expensive art project  at best. I was wrong.   Rarely do you stop at a place like this. I've been twice and both visits were everything I'd want for a nice  casual dining experience. The first time I went we were the only ones outside (it looked like it was going to rain... and it did). The servers offered to reseat us immediately but we actually opted to sit outside and watch the rain. Everything was covered so it wasn't like our server got drenched coming to our table. I had a salmon sandwich  she had a salad and we shared a cheese plate. Everything was portioned and presented very well. The wine and beer they recommend went with the lunch nicely - we had a great time  so we came back a month later. This visit was equally enjoyable. We sat at the sleek bar for a drink before being shown to our table. I feel this spot is the perfect W. Washington Square casual experience coupled with it's nearby neighbor Varga for the rowdier experience.
We came here for dinner on the recommendation of a friend of a friend  who loves it and has been here multiple times.  We liked the idea of ordering a bunch of small plates to share.  It didn't disappoint--everything was delicious and lovingly presented.  We ended up ordering the goat cheese and basil bruschetta (mild but tasty)  figs stuffed with blue cheese and served over prosciutto (rich and pungent)  calimari (which I didn't try)  fennel sausage (tender and flavorful)  two of the cheeses (one was an amazing triple creme  can't remember the other one)  and the chocolate torte.  The cheeses (which are listed on a separate part of the menu--make sure not to overlook them!) are served with sliced bread and are paired with various toppings.  Ours came with fresh honey and some kind of tapenade.         It's somewhat pricey but not exorbitant  which we had anticipated.  The bill came to $80 for five small plates  a cheese board with two cheeses  and two glasses of wine (i.e.  a moderate amount of food for dinner for two people).  You could obviously tweak this depending on your appetite  your budget  or your mood.  It would be a great place to just drop in for a snack.   We ate at one of the cafe tables on the sidewalk  which made for a really pleasant evening.  The service was good but was attentive to the point of being slightly overbearing.  But on the whole this was a very fine meal.  Thank you!
I am a frequent Sunday School attendee and Wash West is my location of choice. The staff is amazing  the selection is perfect.   With so many options being available in Philadelphia and so many new places to try  I am still always going to return to Tria regularly. Great beers  cheeses  wine  food  service  everything. Perfect for any time of the day or occasion.
This review is strictly of the food. I do plan to come back for wine  though. I ordered the garlic rosemary chips. Although they were only $2  I expected a little more. There were about as many chips as you would find in a lays snack pack! The rosemary was very strong  but I like rosemary so I didn't mind. My friend had the pesto bruschetta. If you love pesto  this is the snack for you. It came with two very small pieces of bread with a small amount of goat cheese but absolutely loaded with pesto. The stuff was dripping off. My friend actually had to take some off because it was overwhelming. The atmosphere at Tría is nice and the staff are relatively friendly. If you're coming for wine and cheese I am sure the experience will be more exciting.
Ate on a Saturday around 2 PM - since it was a later lunch there were tons of available tables  which was nice.   Apple Tree Goat Cheese with Basil Pesto Bruschetta - SO good. This one was my favorite of the two we tried.  Pistachio Herbed Ricotta with Lavender Honey Bruschetta - this was my husbands favorite bruschetta - it was also very good!  Roasted Beet Salad - loved it. There was A LOT of goat cheese  so if you don't care for it as much  then ask for them to go light on it. I love goat cheese myself  so it worked out well. It was light  but there was enough to make lunch filling.  Claudio Mozzarella Sandwich - 4/5 stars - really tasty. He thinks it would have been better if the prosciutto weren't crispy since he felt it lost some of its flavor.   Flourless Chocolate Torta - a good end to the meal. Not TOO much - just enough for two people!   This was probably our favorite meal we had in Philadelphia and would definitely recommend!
Museum itself was great.  Many great works housed in a huge  beautiful building.  What I didn't appreciate were the thugs that are permitted to hang around in front of the museum by the statue of Rocky.  They were aggressive and very threatening.  Not sure why the museum allows this to happen on their grounds.  Lawsuit waiting to happen.
I judge new museums against every other museum I've been to  and the Philadelphia Museum of Art one definitely holds its own. I made a day of it by walking the Schuylkill River Trail to the museum  viewing the collections  and eating a picnic lunch on the lawns outside afterwards. It was definitely not a bad way to spend a day.  The museum spans three floors with collections including American art  Asian art  European art  Modern and Contemporary art  Costumes and Textiles  Arms and Armor  Photography  and Special Exhibitions. The museum is obviously architecturally gorgeous  and from the top of the steps it offers beautiful views of the Philadelphia skyline.  The standouts for me were the first floor's European Art 1850-1900 and Modern and Contemporary Art sections. They contained some little-known pieces by artists like Picasso and Monet as well as a very large collection by Marcel Duchamp  which you just don't see everywhere (or  in my case  anywhere outside of art history books). The second floor's Asian Art wing was also really impressive  with fully rebuilt large-scale rooms displaying a Japanese teahouse  an Indian temple hall  and a Chinese reception hall and scholar's study. These rooms were all completely authentic and unique to any art museum I have ever been to  which give it a more field museum vibe and created a sort of living art experience. I also loved the collection of blue-and-white Dutch tiles and Delft-made ceramics  which I have never seen outside of the Netherlands.   On a ratings note  as a Missouri native I am spoiled by the beautiful and free St. Louis and Kansas City art museums. If the Philadelphia Museum of Art was a free museum instead of a $16-per-person museum (not that it's not worth it!) I would be adding on that last star.
This is one of my favorite places to be by myself. I don't play well with others in museums. I enjoy the large open spaces that you can wander through in the museum as well as the connecting grounds that lead to The Waterworks. I've seen a great many exhibits here  having grown up in the area. I am always impressed by the special exhibits that they bring in from all over the world. Some of the highlights certainly include the Japanese tea house and temple as well as some of the iconic Christian art. Of course  no one should miss out on the weaponry exhibit. I really like the new Pearlman Center which recently opened across the street and showcases more modern pieces. Their Japanese Kimono exhibit this past summer was stunning. The whole building receives a generous amount of natural sunlight which is a plus during the gloomy Northeastern winter. I think the docents here do a wonderful job and I always come away from a tour thoroughly informed. The less time consuming audio headsets are equally informative if you rather go it alone. I'm kind of annoyed that they put up a \Rocky\" statue  but at least it's tucked out of the way. I would skip dining in the museum as a meal here can be pretty pricey. Head to one of the restaurants up the road in Fairmount."
I had a week night free and Philly and this was my entertainment of choice. I lucked out and it was Wednesday so closing time is 8 pm instead of the normal 5 pm.   The collection of American artists is really superb. Most people can recognize many of the main artists.   .... And there's also the steps that rocky runs  up in the names sake training montages. There's a bronze Rocky too.
Awesome museum centrally located in the heart of Philadelphia. I knew I had to come when my trip coincided with the \Paint The Revolution\" exhibit. The first thing that caught my eye besides the herd of tourists running up the \"Rocky\" steps (insert Rocky II motivational music) was the architecture of the building. Stunning. I mean  the Met it ain't but it's beautiful  nonetheless. The highlight of the trip was seeing the paintings of Frida Kahlo and Diego Rivera. My only complaints: The  multitude of art 'experts ' who were clearly lacking in spatial awareness. I didn't appreciate being pressed against some fat guys tits whilst trying to appreciate \"The Death of Zapata.\" It was almost the death of me. The other complaint  was paying $9 for the Barefoot wine that I usually get on special: 2 for $3  at my local Rite Aid. However  I do recognize that overcharging patrons is the norm when visiting places such as these  and of course I support art (Especially  when I can get loaded in the process). Totally worth the $20 entrance fee and nearly being smothered."

Southern Sangria is stronger than any European Sangria you've ever had. It's also more fruity  more flavorful and more maroon than any of that flimsy Spanish drink.  Prior to your meal  Ms. Tootsie serves up a giant cornbread muffin as big as your fist. Slather some strawberry honey butter on around the brown top and take a giant bite. The cornbread is as gold as the ripest corn and exudes a flavor akin to midwest state fair corn dunked in butter. It's moist  bountiful and hearty...just the way cornbread was intended to be...  The Chicken and Waffles is simply amazing. Usually not one for any sort of chicken  the buttermilk fry on these strips was too crispy  too clean  too golden not to gobble up. The waffles were fat and golden  and much like their tender counterparts  were smooth and moist on the inside. Served with pure syrup and any other requested condiments  this appetizer is enough for a meal.
This place was amazing! Ms Reni made the most amazing drinks and had such an amazing personality and our waitress  Jiamond was fantastic. Her personality and attentiveness was out of this world. I will be back tomorrow for brunch!
I really wanted to love this place  I really did. The staff was friendly  the decor and atmosphere was great. The food? Not so much. The corn bread which contained too much sugar as it is came with cinnamon butter I believe. I love sugar but I dont want to drown in it. Secondly  everything contained salt  I mean my goodness why? Really? why? The lobster mac and cheese even had obey seasoning on it. I felt like calling my doctor for a prescription of high blood pressure meds right then and there.   The cook had the nerve to come out and ask if I felt the love or could taste the love in the meal? If the love is salt  then yes I taste a whole lot of it.
The food is wonderful but comes in small portions considering the bloated prices.    I had the okra and collard green sides  both of which tasted really good.  The fried chicken was very good as well but for $20 I got a tiny drum stick and smaller than average thigh piece.    The chicken pieces were so small they were more like quail pieces or perhaps hummingbird pieces.  The drum stick was more like a dwarf stick.  I'm exaggerating but you get the idea.  That is my gripe  give me more chicken in my main entrée.    The service was okay albeit a little disorganized.  My food took forever to arrive.    Very modern and well appointed interior.  The restaurant is clearly going for a cutting edge hip hop ambiance and succeeds to that end.    Ms. Tootsie's serves up tasty food but much sure you bring a full wallet if you want a full stomach.
One of my favorite soul food restaurants. I had my 40th birthday party here last year and everything went perfectly from the arrangement and meetings with Mr. Parker to the night of my party. It was one that I'll never forget! I came here most recently with my coworker on a Friday evening and I'd had the Caesar salad with shrimp which was delicious. Tbh  I am usually sick of salads because I end up having to get one since I don't eat any real meats  but when I tell you this salad is the BOMB.com. It is sooooo tasty and filling. It's better than any Caesar salad that I've ever had. I had to cut each shrimp into three parts because hey were so big. My coworker had the buffalo shrimp and they looked delicious. We were both extremely satisfied and to top it off the chef came out to check on us and she was so pleasant. This was just another reason to come back  the ambiance  the food and the service was perfect!
I went with high expectations.  They don't take reservations unless you're a party of 8 or more.  I had no idea that on a Wednesday at 6:15 there would be a 45- 55 min. wait.  Besides the bar area  which was full  there was nowhere to sit.  The upstairs waiting area only had a few spots- all taken.  Maybe it was an off night  but the food was just OK.  It was problematic that I don't eat meat.  Since all the green vegetables were cooked with turkey  I decided to order the caesar salad with grilled salmon.  Dressing was unremarkable and served on the side.  The crouton coverage was too heavy.  Might have been different if they were special in some way  but they tasted like they came out of a box.  The salmon portion was sizable- maybe 3/4 of a lb  but it was pretty tasteless.  Cornbread muffins were fresh and hot- decent tasting  though I would have ratcheted back the sugar.   I tried some of my friend's sweet potatoes.  They were OK.  She had shrimp and grits.  I also tried the grits.  Very bland  sprinkled with shredded cheese.    I rate them 3 stars because our waiter was very nice as was the hostess and other staff.  Speed of service was OK.  Atmosphere was nice.  My friend wanted dessert to go and asked after the check had already been prepared.  He brought the cake and didn't charge us.
Good drinks  good vibe  nice view.  Been there a bunch of times -- yeah  I'm a fan. Great place for a romantic dinner or simply to start the night with friends. I can't really rate the food 'cause I haven't had an official meal there yet (only small bites)  but the service and the drinks are good -- some days better than others  but still acceptable. I like to sit on the balcony when it's warm out. It's a fun experience.  Definitely a fan of their restroom  too. It is clean and elegant  I like that! :)  Going there with a large crowd can be a pain though because the sitting is so...awkward. That's what I don't like about XIX. That  and that usually the people who go there are such snubs. Yikes.   But overall  it is a good place.
I've been here a few times  once for dinner  once for Sunday brunch and another time just hanging out at the bar. I've enjoyed myself everytime! I've gotten the steak both times (dinner and brunch)...D-E-L-I-C-I-O-U-S. I also ate several slices of cheescake at brunch until I was completely stuffed. The service is alway great...I love this place.
The decor and  view from this restaurant is absolutely gorgeous... A definite hot spot for a romantic dinner.  Food was cooked to perfection  service was exceptional - very courteous and prompt. I'll definitely be coming back!
Excellent food  lovely ambiance  light and airy  not too noisy  with pleasant and attentive servers. But that's not all. The 3-course prix fixe lunch is my favorite. The first course is a buffet of salads  meats  and cheeses. Then you get a choice of entrees made to order. The arctic char with broccolini and couscous was delicious! Finally  a dessert buffet with a nice variety of small portion cakes  cookies  and mousses. I have been there for lunch many times and will return and recommend it to friends.
I've ended up here twice within the last week with friends  and I have to say I'd forgotten how much I love it. For some reason I never remember to go to XIX - maybe because it's on the 19th floor of a hotel  or because it's in the middle of Broad St.  but regardless I have resolved to start going there more often.  The ambiance is spectacular - one of the most physically beautiful bar spaces in Philly I'd say  with that old hotel bar glamour that is harder and harder to find these days. High ceilings and windows  low light  a fireplace in the winter (which is reason to go there in and of itself) and gorgeous balcony seating in the summer...if you need a romantic and lavish date spot  this is your place.   There is a fairly good selection of wines  although they're categorized in a slightly odd way (e.g. full bodied  medium bodies  etc.)  that are not exorbitantly priced for a hotel bar. The calamari is also wonderful  although the cheese plate is a bit sparse for the price tag. It's also not too overcrowded or loud on Fri and Sat nights  which is a welcome respite from the midtown/Sansom St. craziness.
Mice!!!!! Just left happy hour and saw a mouse running around the bar. Definitely not returning!!!
I took my bf to celebrate his bday.  I opted to book via OpenTable-- seamless process.   We were running late (per usual) I called to inform the hostess and they were accommodating. The ambiance is to DIE for. The pearl chandelier is simply breathtaking.  After checking-in and admiring the architecture  we were seated. Our waitress (I forgot her name) was an ANGEL. She was very well versed on the menu and made meal and wine pairing suggestions. I opted for seafood and the beau ordered a steak-- heavenly! We had the last seating and not one did we feel rushed! Our waitress went over and beyond  she was very friendly and personable and helped in adding special touches (like lighting a candle when dessert came out). I also asked if we could take pictures on the balcony-- she said it was closed but she could see what she can do. Sure enough  at the end of dinner she opened the door for us to take pictures. The view was AMAZING. Our waitress was soooooooooooooo gracious.   I definitely recommend this place for a romantic dinner  wedding  rendez-vous--- whatever.   After dinner  we went to the lounge to order more drinks. You could honestly make a night out of just the lounge area.
This is my first review on Yelp and sadly I have to give what used to be one of my very favorite happy hour spots one star. I have been coming to XIX for happy hour for years and I have always loved it. It has a relaxed vibe  its beautiful  and has great bar food. I went today to celebrate a friends birthday with a few drinks before venturing out into the city's nightlife and was greeted by a mouse in the lounge area! Totally unacceptable for a place of its caliber and reputation. Get an exterminator please!!!
Good fries! Sit at the bar  comfy chairs and you can see the view of the city a little higher up than in the lounge. Happy hour is pretty good  the staff was attentive and the atmosphere is great!
wm mulherins did not disappoint! Weve been wanting to come here for a while  and it was definitely worth the wait. From the intimate seating to the awesome music   we were happy from the beginning. Then we tried the food   and it was all delicious.  We started with the veal tar tar toast  ceviche   and octopus.  The tar tar was very unique and delicious. The ceviche was accompanied by grapefruit which we loved. Then I had a pasta dish and my husband had the halibut. We were given the option to add truffles to any of the pasta dishes for an extra 10 dollars  it was totally worth it and I highly recommend you do so! Everything was served as soon as it was ready  so all the food came out hot and fresh. The cocktails were great  but also had delicious wine. There is a log bar area with a few tables  where we actually sat and ate. There is outside seating with heat lamps. The vibe is really chill  yet the food is on another level. The experience is definitely worth the overall cost. We were not rushed either   everything was paced nicely. Will definitely be going back soon!
Enjoyed a superb meal! Every dish was amazing. The food was always good here  but the new chef has taken it to another level. Especially good were the corn pizza  artichokes  corn ravioli  zucchini salad  and seafood mixto! The octopus was almost inedible the first time we ate here  overcooked and oversalted  this time it was fabulous! Terrific wines by the glass too. Even the bread is better than most. Excellent service as always. Will not hesitate to return or recommend this restaurant to friends and visitors!
This place is a one and done' Had they printed the prices on their website  may have been a none and done. Hate to be the \debbie downer\" but someone has to provide a dose of reality. Showed up without a reservation  and  having now experienced the place  am surprised we needed a reservation. Regardless  there were only tables out on the sidewalk (where the El passed overhead- nice touch every 10 minutes). This was fine as I did not call ahead. When we arrived there were a couple tables outside so figured out we could get seated quickly. Not so. \"They were not ready yet  why don't you have a drink at the bar\". After ordering a mixed drink and beer at $25 including tip  all of a sudden the tables were ready. I fell for this again  my bad. Lets cut to the chase  in addition to the bar tab  the \"dinner\" consisting of 1 beer  small plate of seafood mix  ribs ( at $9)  suckling pig  pasta and dessert with 1 coffee...$110 w tip. The \"suckling pig\" was a piece of pork  the volumetric size of a deck of cards (with good portion of fat) over beans  the mix was about 2 tablespoons full of seafood  the ribs were 3 small ones. The pork was $31. NOTE_ They tout this as a \"sharing:\" restaurant..How do you share 3 small ribs between 2 people? Don't go by the photos. If you get the camera close enough and use a small plate  it does look like you get a good portion. This place is for the \"uber generation\" who need to be seen. Personally  there a many places in the area offering better value to be \"seen in\". There are no drinks or food worth that money  $135 for 2 people. And if you want to spend a fortune just to \"be seen\" or name drop. spend it at Capital Grill or Ruth's Chris  at least you won't walk out hungry."
Best dining experience I've had in Philadelphia  Loved the interior  food and staff was extremely friendly in a genuine way. Can't wait to go back.
Great new place. Full house on Thursday night. All food was made perfect and service was on the spot Thanks stuff and chef Chris for a great experience
Really great service and beautiful restaurant. Cocktails were also very good.   However  the food we ordered was lackluster in comparison. Very small portions for the raw plate and pasta. Hanger steak was tasteless. Pizza was worth getting.
I was taken here for my birthday after wanting to go for a long time.  Everything was perfect  including the waitress  who explained everything  knew a lot about the menu and wine and had a voice that carried above the din in the room.  Standouts were the octopus  mouth watering  perfectly seasoned  and the dates  which I wouldn't have thought to order if not for reading about them beforehand.  They were off the charts  perhaps the highlight of the night.  WE had a pasta special and the duck  both superb.  I will be back soon.  I will be dreaming about that meal for a long time.
I went for brunch on Saturday and it was so great I went back on Sunday! We had the asparagus salad seafood Mixto  mushroom pizza salmon toast volcano eggs pasta. Quite literally everything was delicious and perfectly executed. The asparagus salad was something I've never seen on any other menu. My favorite was the truffle pizza  rich and perfect. I can't wait to go back for dinner.
Thoroughly disappointed that Barcelona Wine Bar \lost\" the reservation my mom made (party of 4) for 7PM yesterday evening. When we arrived the place was absolutely mobbed  and we were barely able to walk in the door which instantly gave me a bad feeling.   The hostess was nice enough  at first  but as time passed it was obvious she was stressed/frazzled and couldn't handle the pressure/volume. Part of me felt bad for her the other part was so irritated. My mom and I tried helping the hostess look on the reservation sheet for our name however the penciled in writing was so haphazard and some even faded it was nearly impossible to read the names. The hostess offered to add us to the wait list which appeared to have several names already waiting  unfortunately she was \"unable to quote us a wait time\" which was insanely frustrating. I  previously worked in the food/beverage for quite some time  first as a hostess  as well as a server and bartender. Not once have I heard of not being able to quote your guests a wait time! Needless to say we left to eat elsewhere.  First they lose our reservation and the best they can do is put us on the wait list - without an estimated time? Totally bummed out  hopefully our next trip there (whenever that may be) will fare better. I advise calling at least a day or two in advance to confirm your reservation as they seem a bit unorganized."
Nice fare - really enjoyed the cheese board  calamari  & bacon wrapped dates. Hanger steak was cooked perfectly. Portions were generous for tapas plating. The very reasonably priced full-bodied red blend we had was awesome & the dessert sherry our server suggested was excellent. Would recommend to anyone in town or visiting as a great experience all around.
I went with friends here for dinner and we had a great time! The food was great  the wine was fantastic and the ambience was beautiful! Our waitress was friendly and took care of us on a super busy night! We were a group of six and ordered 5 different tapas which were portioned well. The ham croquettes were fantastic as was the butternut squash! We also did the chorizo with fig  the potatoes  and roasted carrots! They were all really good. We all had a hard time picking our favorite. We then shared the seafood paella which was flavorful!  We got there early enough to get one drink on the happy hour menu which I got the white sangria which I was very happy with. Everyone else enjoyed their drinks as well. We also shared a bottle of wine which our waitress helped us pick and it was perfect for our meal!   I most definitely will be returning when I'm home for visits!
Had a 7:15 reservation  but when we arrived the host told us that the reservation got lost in their system. Waited at the bar for a half hr before checking back in with the host (who forgot who I was). Finally  45min later we were able to get a table. Would've been better without the wait or if they had offered to comp something  since the error was on their end. Two stars because the swordfish was delicious!
We went before dinner for cocktails and some appetizers. We will absolutely be coming back. A+ service  cocktails  and tapas! We had a cheese plate (with drunken goat & blue cheese)  the swordfish  and the gnocchi with duck. Absolutely incredible!
Loved this spot. After just visiting Barcelona in Spain and coming into this restaurant  I felt like I had returned with the atmosphere and all tapas. I recommend getting the pitcher of sangria about 3-4 glasses for a table of 3 couldn't get any better. We got the mussels  patatas bravas  pane con tomate all very delicious. This is definitely a must eat in Philly.

This place hits the spot.  I didn't try the coffee  but went with tea instead  so I can't comment on the coffee's goodness today.  What I can say is they place great tunes  there is plenty of space  the wifi doesn't poop out  and the decor & vibe of the place is perfect for me (kinda country  chill).  The egg sammy I ordered is delish  hot and cheesy.  I'm working here very productively  with a view of the horse stable out the window.  So I'll definitely be back here to work and chow down again.
I've never eaten here  so I can't speak for the food. But the coffee is delicious  the staff is always cheerful and very helpful and eager to recommend their favorites. Very nice ambiance for sitting and relaxing with a cup of coffee and a book -- nice cozy atmosphere for a city coffee shop.
Visited here last Sunday & really enjoyed the food  and live music!  The service was a little slow but the music def kept you distracted!  I ordered the chicken livers & gravy & a salad very yummy! (Asked for extra gravy)
OMG.  We went last night for the all you can eat Crabs  and they were absolutely awful.  In fact  all of the food was vile.  The crabs were so small and all of the meat stuck to the shell.  So NOT worth the money.  I could have made my own crab legs for half the price and they would have actually tasted good.  AWFUL AWFUL AWFUL
Ok Comedy on Monday Nights was soooo good. I had the appetizer sampler I posted a picture  more than enough food to share. We had no idea it was that big but it was delicious  especially the cat fish and corn bread. But get there early or make reservations for the shows because it gets packed and you end up paying to stand and watch a show. Great for the nice summer nights  and contrary to other peoples opinion  I like the new locations  more parking right by the movie theater  so you can get drinks before or after watching a movie and its right off the highway. I frequented this venue over the summer and have no complaints.
Warmdaddy's is the number one soulfood restaurant in Philly.  A bit pricey  but the service is always excellent and the food is amazing.  I make it a point to come here at least a few times a year.  The portions are very generous and the live music makes it a memorable dining experience.  Parking is ample as well.  There's also the option of having meals outdoors  either the patio or the rooftop (beautiful view of Philly) - no cover charge for outdoor dining.
The food is good.  But don't expect good service.  My husband and I went there for a Friday night dinner. We were seated outside due to the wait time. This suited us just fine since the music was too loud and over powering for me.  Once seated however the wait staff forgot about us.  I had to go and find our waitress just so she could come get our drink orders. At this point we knew what we wanted. Our order took so long that our appetizers and meals came out at the same time. Some sides never made it out. The wait for the check and even to pay was even more painful.   I might order take out but never dine in again.
If for nothing else... I give them a five for the cornbread. I consider Warm Daddy's to be a Philadelphia treasure! Local talents are amazing  the cost atmosphere makes it feel like a speak easy or smoky jazz club. It's nice to feel like a part of a community.
Awesome southern comfort food in the heart of Old City. The management here is great and they make you feel welcome. They have live blues music on the weekend and that helps make the atmosphere really chill. The food was excellent: chicken and waffles  gumbo  fried catfish  mashed potatoes  collard greens and candied yams. They also serve some strong mixed drinks  which are very  very good. The service was very attentive and accomodating  I highly recommend it for a fun night out.
Great tap list and excellent service.  Our server was on the spot whenever we needed something (dropped fork  the next pint  etc).  Good burger too - the ability to add a fried egg was a nice plus.  Wish it was Wednesday so we could have had the Berkshire pork.
This place is ideal if you want to stop in for quick drink and appetizer and watch sports. Inside there's a main dining room area and 2 bars on opposite ends. This place also has a very decent beer menu  as well and cocktails and wine. I recommend the wings  as the seasoning is sweet and has a kick to them!
Nice beer selection  outdoor dog friendly seating and good food. The inside restaurant is beautiful and it seems like a great place to watch sports (large projector screen with TV above the bar).
I love love love the original location  so I was absolutely thrilled to hear City Tap would be coming to logan square (much easier to get to from the train!). They have good beer  good food  and an overall great atmosphere. While I am sad that this location doesn't have fire pits like the original  I hope to frequent this location in the future for happy hours and nights out.
I went here late one night months ago with friends and have been meaning to write a positive review since! After putting it off  I'm finally making sure to do it. That's how much I liked this place. We arrived to a very warm welcome from the bartenders as if they new us as a regular customers forever and got some free welcome shots from a very friendly bartender who's name I can't remember. The staff was attentive and a lot of fun. Would definitely recommend you go here if you're in the area!
This was my first time here since this became tap house and I must say I like it. I've been to the one in university city a couple times and while I do like this location I prefer the logan square one since it's in a ideal location which is near center city.   This place is very ideal for fans as there are TVs located pretty much everywhere one looks  including one huge flat screen which is mounted above the bar. The food is what one will typically Find in a bar ie wings and nachos. The main highlight on the food part was the pulled pork nachos as it had this nice cheese sauce that went well with every bite of the nacho.   All in all  it depends on what you are coming in for. If you are coming in for watching sports  having some good beer and decent food then this is the place for you. The atmosphere is inviting and the wait staff are friendly
Delicious. So happy I Yelped for a restaurant closer to home and stumbled upon this. It's small and pleasant inside with some decent hip hop setting the mood. The menu is small  but packed a punch. We ordered the Duck Fries  which were heaven. Fries smothered in smoked gouda   shredded duck  and scallions. For 8 bucks came a pretty large bowl that I couldn't stop picking at. I ordered one of the specials  the scallop and foie gras  tacos...wow...so good (then I read the origin of foie gras and hated myself  but aside that...). The person I was with ordered the pork roll burger  which I tried of course. It was incredibly juicy and cooked perfect. I will definitely come back here. Definitely.
Where do I start. I ordered food to go it was my first time here so I ordered the Blue Jawn  burger no lie  I vomited we had to hurry up and pull over. I ordered the general tso chicken tacos not good and the sauce was too sweet. They were using bare hands to prepare the food which was already a turn off. The place is small and tight everything is everywhere. My 3 year old daughter brung me spray bottles I guess they had in her sight. The Mac and cheese were like baby elbow and partially hard . Looks are very deceiving  everything looks good but I wasn't happy.My baby didn't even like her Mac and she love Mac and cheese and my son love General tso chicken but not this one. I will not be returning ever. The prices were very high too.The food was being prepared or put together after food was cooked at least when a pizza goes in the oven  and bake it kills the germs.You'll do everything bare hands before cook and after and I have the pic of that too I can post it. No sarcasm needed. Thank you Nick. No everything wasn't as quack up to be
If you were able to give it more than 6 stars  I would. The first exposure to the duck I had was at the beer and bacon festival where they had their tomato soup with garlic pulverized bacon. It was so good they ran out about half way through the festival.  Last night was my first time at the actual restaurant. It was a large group so in total I tried the blue duck fries  general tso's wings  the pork roll burger  house blend burger  quack and cheese and classic Mac. If you have a large group make sure they want to share because you're going to want to try everything. It's all amazing and will make you want to come back the next day. Looking forward to trying the brunch menu.  The managers also stopped by our table since it was my friends birthday. They made sure everything was perfect and I was really impressed with the staff.
Love this place! I stopped in for brunch on Saturday and had a fantastic experience. Our server  Steph  was phenomenal. She went over specials of the day and ensured that we had a great meal. We started with the Blue Duck fries. They were PHENOMENAL! Definitely get them on every visit. I had the duck benedict and my friend had the chicken and waffles. Both were good. The chicken was nice and crispy but could have used more seasoning. The waffle was fluffy and delicious. The duck breast was tasty and went well with the cherry siracha sauce but I didn't like how the sauce tasted with the rest of the dish. It was taken off of our bill without me asking although they prepared it properly  it simply wasn't to my taste. Overall we had a great experience here. I def recommend it.  (Oh and it's BYOB. Wish I had known to bring a bottle)
(to the tune of \The Mack\" by Nevada feat Mark Morrison and Fetty Wap)  Yelpers tried to tell me so (yes they did) But I didn't wanna go \"Gotta car?\" gotta say no. But my mouth wanted to know. Yeah  I felt it from the start. From my tummy to my heart When my sister was in town We were headed to chow down.  No lies to me  (All those reviews weren't kidding) No lies to me Oh my god baby... Take a bite!  Blue Duck  it's like Quack (once again) Blue Duck  it's like Quack (top of the charts) Blue Duck  it's like Quack (gotta go) You know that I'll be back.... Blue Duck  it's like Quack.  Wow. Worth the trip is an understatement. While the schlep was a bit out of my usual trip for eats  my baby sister is all about that burger  and we'd heard only the best. We went later in the day  around 2pm  but service was still incredibly slow (frustrating because there weren't a ton of folks inside  but maybe they were recovering?) This resulted in us getting our duck fat cheese fries WAY before our burgers. We TRIED  to wait for the burgers  but our stomachs rumbling drowned out that idea. The mac and cheese  the cheese fries  the burger.... Every bite was perfect. I only wish that the food came out all at once like we asked. Oh well....  The Beast of Northeast (Philly) [wild boar and beef patty  smoked gouda  sweet tomato jam  crispy sriracha onions  and bacon on brioche] was insane and  IMHO  tastier than her pork roll burger  but that pork roll was sizzled to perfection.   I'll be back for the Quack and Cheese  next time a buddy with a car is feeling adventurous. Hopefully they can speed up the service a bit  don't want all that gouda sauce getting cold!"
Ever since I started working in the area a little over a year ago I dropped in to The Blue Duck for lunch and it quickly became a favorite.   The quack and cheese  duck fries  and anything off the brunch menu on Sunday's are out of this world. Dinner entrees are exceptional all reasonably priced for the quality of food.   I've never had a bad experience here. Great service and great atmosphere.   I try to make it in for one meal a month and if you've got the time you should too.
The Blue Duck is located in this very small plaza filled with very bland store signs  but don't let the outside appearance fool you. Inside is very cozy  clean  and nicely decorated.  The staff is always friendly and attentive  and the food is pretttty good. Their duck fries are amazzzzing and the portion is huge! I can never finish an order with my girlfriend and it sucks that it doesn't taste half as good when heated up later. The burger here is really big and unique  but I feel that the meat blend can be a bit better as it seems a bit tough. The brunch menu here is a lot cooler than the normally offered lunch menu (the duck fries are still offered!)  and would much rather come for when they are offering brunch.
The food was yummilicious!   The fries could have had alittle more shredded duck   but the overall flavor was spot on.  Duck Fat!  The Tso  wings writer the wasabi blue cheese dipping sauce was wonderful... not too spicy which was  perfect for me.  One complaint... . our waiter was packing our food and instead of using a utensil he used his fingers.... I was not happy about this... and will pack my own food moving forward.  So that means I'm going back!
It's nice to have a decent culinary option in NE  but I hear folks talking about this place like it is the second coming of Christ!  The duck fries were some of best fries I've ever had.  Get them  won't disappoint. The duck sandwich and pork roll burger were both bland and barely mediocre. Salads were grossly overdressed.     I'd try it again if I were in the NE.
Very good place. It was a bit noisy at first since the tables are right against the bar. The activity at the bar was intense and loud - some had already imbibed quite a bit by the time we arrived for dinner. The food was good  the service good  and over all this was a fun place to dine.
Ran into this place on a rainy Philly night and had a nice  cozy meal. The service was very relaxed and friendly. Had a wonderful glass of wine and a few small plates to share. We really liked the food and decor of this place. It was pretty evident though that the charm of this place is the outdoor seating and generally for brunch. Next time.
I came here by myself for dinner and sat at the bar. This was a good choice for solo dining  plenty of small tables and bar seats  and lots of options for wines by the glass.  My food--lobster fra diavolo with housemade pasta--was delicious. I probably would have liked it just a touch spicier  but other than that it was pretty perfect  perfect portion size  plenty of lobster  and well-cooked pasta. The wines-by-the-glass list included choices starting at $10  and both of the ones I tried were tasty. The complimentary bread was a bit hard and could have benefited from a toss in the oven  but it was still tasty.  My only complaint about Rouge is how cramped and crowded it is. It was not full to capacity when I went  but it was still uncomfortable sitting at the bar and having people constantly bump me trying to negotiate the small space. If they ever decide to do a big renovation  I bet they could make this place much more ergonomic.
I'm in Philadelphia for work and looking for a chill place to grab a drink or two and a bite. Found Rogue and have to say I was very impressed. I sat at the bar and the place was surprisingly busy for a weeknight. Katie behind the bar was the perfect bartender. Nice and attentive without being too familiar and made one of the best cosmos I ever had. I had the tilapia tacos which were the perfect size. Spicy but not hot. Well seasoned and just large enough. Good to split as a starter. I would definitely come back  at a minimum to have another of Katie's killer cosmos.
Went here with NYE with a rather large party of 7 (large for the space) and at no fault to Rouge  we weren't seated until 25 minutes after our reservation. The party before us was enjoying their dinner and taking their time. They did offer us a cocktail while we waited  which was lovely.   We ordered the 5 cheese platter which was lovely  great cheeses  although I have no idea what was what!   Next was the seafood apps- calamari  escargot  and mussels. I'm not as adventurous with calamari  but I liked it. The mussels were delicious and bread was plentiful for dipping in the sauce  but I have to say the escargot with goat cheese was hands down the BEST escargot I've ever had. EVER. I told my boyfriend I wanted to come if only for wine and escargot.   Main course was next! There were a good amount of NYE specials  but I opted for the salmon and kale. Kale was perfect  salmon was great. I also got to try one of the NYE specials of scallops and a truffle oil risotto. It. was. epic. I'm a huge fan of truffle oil and wish I could have had more.   Over all  top notch experience and I look forward to going back  and perhaps some alfresco dining in the spring and summer!
Excellent service and food was wonderful. We did not have reservations for lunch and when we walked in they assisted us in getting a table by the open window  which was very kind considering it was a perfect day and perhaps would have been filled quickly. I would return in a heartbeat! Highly recommend.
I enjoy the ambiance  décor  food  & the cocktails. Rouge is right across the street from Rittenhouse Park. It is a good place to take a date or meet up with friends for some drinks & dinner. You can always sit outside  or by the bar to get a good view.  The dress code for this place is casual but  it's a more sophisticated casual. This isn't your let me throw on jeans & a t-shirt type of place. It's a bit more dressy. I can appreciate that. This place seems to target people in there 30's & 40's but  I also see people in there 20's as well. It is definetly  a more mature environment which is nice.  During my most recent visit  I ordered the cheese plate that came with 5 different types of cheeses. I loved the french bread that came right along side of it. Everything was very fresh & flavorful. Cheese plates are usually a hit or miss for me. I enjoyed mine here. It comes with jam  grapes  & slices of apple. I really like the portion sizes here as well. Not to big but  not to small either.  If you are looking for a posh  upscale yet laid back atmosphere then Rouge  is definetly the place to go.
Rouge Bar Score: 21  Burger Quality: 5 Bun: 4 Fries: 4 Extras:  4 Value: 4  2 Sentence Review: Great burger...you will taste the seasoning on the fries for days.  Atmosphere is similar to my Aunt Pats dining room.   -------------------------------------------  How does Burger Einstein's rating system work?  - Burgers are rated across 5 categories (see below)  - Category scores can range from 0 to 5  with 5 being \Outstanding\".    - Total score (out of 25) is determined.  Scores above 20 earn 5 Stars (rare)  between 16 and 20 gets 4 stars and so on    Burger Einstein Categories  1. Burger Quality: Good meat or Bubba Burger?  2. Bun: Does it compliment the burger or overwhelm it?    3. Fries: Do I accept the guilt or compare them to my Ex  4. Extras: Wild card.  Could range from Cheese to bourbon to atmosphere  5. Value: Burger cost relative to smiles (heavily influenced by how much bourbon I drink)"
best burgers  hands down -- but don't give in to the pressures of pretense  go comfortably  yet  respectfully  and you'll have a great time!
Awesome happy hour and food specials. A bit out of the way for us  but we stop by occasionally because everything is so cheap but high quality during happy hour.
Certainly one of the highlights of my time in West Philly was the opening of Local 44. It has served as a great locale to grab a high quality beer from all the US (Great Lakes  Ommegang  Sierra Nevada) and eat some decent pub grub. Its a great place to go on a Saturday night to meet up with friends and start a night there.  We have been coming here after our softball games and have found it to be a great locale to hang out with the team. It doesn't have quite the right seating set-up for out team  but we make it work.

I have heard and read great reviews from many people about Dante & Luigi's  I was not disappointed. Every entree we had was delicious  the apps. and desserts were just as good. I've had better meals  but not by much  and never at this price point.
Don't try to bring a young child here  because they don't have highchairs or booster seats for little kids. So much for families being welcome... as long as your kids are old enough to sit in regular chairs I guess. Was pretty irritating to be turned away after braving a pretty nasty rainstorm specifically to go here on our last night in Philadelphia.
I'm a spoiled New Yorker  what can I say?  When I heard this was the oldest Italian restaurant in Philly  I had high expectations. When I saw the prices  I had higher expectations. Expectations not met.  I had the spaghetti with bolognese sauce which was good but I have had so much better. I think the sauce was the most disappointing part of the meal.  The bread served in the beginning is fresh and I did appreciate the sweetness of the vinegar to accompany the olive oil. The sautéed spinach was too bitter  but the Italian sweet sausages I tried were good.   This is a descent place but I mean descent and I had expected 5 stars.
(Let it be known this review is the prelude to a pickup order that's going to be placed immediately after submitting it. )  After a 2.5 month wait  I had the pleasure of having some fantastic food here. I really enjoyed this place and although I need to try it a few more times  it's likely this could supplant DSG as my go-to spot. It's also two blocks closer to mi casa y workplace. We need more food closer to Broad Street that's not of the  Golden Arches and sub-par pizza variety. This is one step closer to achieving this dream.   Oh yes  the food: _________________________________ Original Egg Roll: The truth.   House Pork Buns: Could eat this thrice daily no problem. So good.  Salt & Pepper Shrimp: Tasty. They have eyes. They are watching you. Judging you.   Shrimp Shumai: The best I've had in the city  maybe ever (no really maybe).  Scallion Pancakes: Very tasty and not super-greasy.  Minced Beef Dumpling Soup: Not bad  only ordered it because 1/3 of our triumvirate that day keeps kosher.  Chinese Broccoli: Always order Chinese Broccoli. Always. They will test your skills with a chopstick a la Mr Miyagi.  Welcome Nom Wah. It's a pleasure to have you. _________________________________ Eat here now  eat here often.  - ß
First timer  excellent food  lovely staff and atmosphere.  Can't wait to go again and try more flavors
A good place to get Dim Sum (not the cart kind) when you are craving Chinese food! The sticky rice in lotus leaf and steamed pork buns were delicious. Not my favorite soup dumplings I've had  however. Atmosphere was nice and all the food tasted very fresh.
Good food but unbelievably the chef and manager started screaming at each other in the middle of the restaurant in chinese  only to end the yelling with the chef yelling WTF in English. There were young kids in the restaurant for crying out loud. The manager then goes back into the kitchen and yells some more. Up until that point it was a nice atmosphere and decent dim sum but that was just plain indecent. Like out of a movie or something. Settle your differences in private  not the middle of the restaurant while your patrons are eating.
I've frequent Nom Wah in NYC so when in Philly  I needed to stop by this establishment. I went on a rainy Tuesday afternoon and it was a bit quiet. The decor was age old but new aged if that makes any sense. We got the dumpling sample  roast pork bun  spring rolls  shrimp rice rolls and pork sui mai. All were cooked steamed to order which meant the food was piping hot. They also have a good selection of beers and a full bar. Dimsum and drinks??? I wouldn't decline that invite any time.
The dim sums were delicious  favorite was the shrimp shumai and the Shanghainese soup dumplings. The friend noodle was a bit too oily for me but the house special fried rice was delicious. We made a reservation through opentable and put table wasn't ready when we got there so waitress about 20 mins. All in all a good experience. Also saw that it was BYOB
Undoubtedly the best traditional dim sum place in Ctown Philly. The dim sum is made to order  you pick from a wide selection of traditional dim sum menu. Everything we ordered was solid/above average (fried noodles in soy sauce  turnip cake in xo sauce   spare ribs  fried shrimp balls  and shrimp rice rolls).  Price is above average but you get what you pay for. We ended up dropping $50 between 2 adults and a toddler but left mighty full (we prob over ordered). The interior is classy and more importantly  clean. Chinese lanterns hang overhead with comfortable seating and a full bar to boot.  Nom Wah caters to everyone  young and old. Those yearning for traditional dim sum appetizers yet dislike the old way of doing things (there are no old ladies wheeling carts of overcooked food here  and that's a good thing  folks).  Located on the outskirts of Ctown  which is another plus for those wanting to avoid driving through the hustle & bustle of Ctown.
Mmmm. Just had a really great lunch here. It's a perfect mix between a sit-down lunch and a food truck lunch. Quick  and seriously delicious  but you can also sit. Not cheap  though...but worth it.   I had a spicy pork taco (2 minimum  so I shared) and seriously? I could have eaten 4 of them. The tortilla  which is clearly not exactly a tortilla  is almost sweet and it plays so well with the flavors of the spicy korean pork. And the sauce...that sauce is talk with your mouth full \dis is soo good\" type of sauce. Going to get a bottle for home...  I also had the Dak Bulgogi (spicy chicken bulgogi) and it was also really good - but I did a lot of sauce dipping  making it even better. My rice was a little on the sticky side  but it was still a really solid lunch. My bf got the spciy pork rice dish in a stone bowl (lunch special 3) and it was also tasty.   Service was fast  and good. I'm a fan."
This place is very quick service and the owner and people working there are very accommodating. We ordered the vegetable steamed dumplings and they were good. It came with some edamame and some carrots which was a little strange. We also ordered the dol sot bibimbap  the soon duboo and the bulgogi. The food was pretty good  the meat could have been a little more flavored. I also wish they had spinach instead of romaine lettuce in the bibimbap. Overall  I'd go back. Not mind blowing  but does the job if you want some quick Korean.
Pretty good dol sot bibimbap: piping hot (seriously steaming!)  but the flavor was lacking something. Great kim chi and loved the pickled radish and cucumber. Overall  a little pricey for what you get  but good for a Korean-food craving!
Kimchi Pancakes - good flavors   a little soggy. Beef Bibimbop in Sizzling Bowl - fresh ingredients yum!  Thanks Zagat!
THIS PLACE SERVES OVERPRICED  BLAND  LESS-THAN-MEDIOCRE FOOD. UUUUUUUUUUUUUGGGGGGGGGGGGGGGGHHHHHHHHHHHHHHH. Don't waste your money here.
Giwa Taco. That's all that needs to be said.  Amazing.  Not very well air conditioned and simple small venue  but the price is extremely nice.  And the food is very good.
Mmmbibimbop! Such simple food  but delicious. Lunch time drop by at this tiny place  got the bibimbop with tofu  friend got it without. A delight for lunch  not too slow (not too quick either  though). You may have a problem finding a seat  and your pocketbook will be a bit lighter (but your stomach will be heavier so it all balances out)  but a good treat to forget about work for a while. It is definitely overpriced for what you get  so I won't be getting here too often  but I will return. If it was more reasonably priced  I'd give it 4 stars.
I love this place! I think I must come here every week  maybe even twice a week sometimes.  The food is always fresh and flavorful  the staff is really nice  and the food is served quick.    I like their Dak Bulgogi (spicy marinated chicken) and their buckwheat noodles (only available during the summer). Their new dish  Giwa Taco  is threatening to be a new fav!    Most dishes are served with a little kimchee and pickled vegetables on the side.  Yum!
I wanted to like this place  I really did. Since moving to Philly  I've missed good ol' Korean food.  This place reminded me of a restaurant near our dorms when I studied abroad in Seoul  so I had high hopes.  Unfortunately  the food kinda fell flat. Service was good and quick  but my dol sot bibimbap was pretty flavorless  even with the pepper sauce. I was expecting bulgogi for the meat  but it tasted like flavorless beef. My fiance's bulgogi was definitely better. I'll try that next time  if we return.
I feel the need to update this review based on an experience had here last evening.  The service was non-existent.  It took 15 minutes for water and someone to open our wine  20 minutes to order  20 more minutes for the soup  and then half of our group of foud were given their entrees and the other two waited 15 minutes for theirs.  Also  one of the late entrees was completely the wrong dish.  When this was brought to their attention they didn't even apologize.  It is one thing to be short staffed and acknowledge that the service is suffering and while I don't expect a fine dining experience at these establishments-- they did not apologize or even recognize that there was a problem with the timing/service.  Also-- portions were incredibly inconsistent.  One of our party got drunken noodles  which are ordered often and are always great but there was 1/3 of the usual size dish.    I will not be back.
Not the most decorated place  but great food  great hospitality...its BYOB so ensure you get your \stuff\"...Thai sausage with the ginger julian is one of my favorite...decent menu..."
3 years ago  I couldn't stop coming to Erawan.  Now  I can hardly finish my dish because it's doused in sugar.  They also don't seem to want to listen when I ask for extra spicy.  Unfortunately  even a bunch of hot chillies may not be able to mask how sugary every single dish they serve has become  from the pad thai to their curries to their duck entree.
After being at the chinatown location  I was skeptical when my friend picked this spot for her bday dinner  but it turned out a lot better than their other location. I'm confused why it was such an upgrade  as it's the same restaurant as the other location  but the food here was a lot more flavorful.   We came with a huge group of 20 something people and they were pretty nice in dealing with our rowdy group of deliquents. I know it's very difficult for a kitchen to get 20 plates out at once but this place would get more like 3.5 stars if possible because some dishes came out 45 minutes before others and they were in the same \hot noodle dish\" category. They had a full house and other large parties so its understandable  but 45 mins between similar dishes is pretty rough stuff.  The atmosphere was average and service were pretty nice  and it seemed clean enough. Nothing spectacular but I'd come back. Our food was pretty delicious so I have to hand it to them on stepping up their game there. I got pad see ew which definitely rocked and all my friends had nice looking plates. I was bitter with the other location's pad thai that only had half the normal ingredients  but this location included the usual tasty works. nice job guys. give the chinatown location some pointers.  Also  thanks for being byob and opening countless bottles of wine for us  as we waved bottles at random workers in far from sober states."
Food here is good  but rude service and understaffed. The couple times I have taken out from Erawan I have been left standing by the front desk for at least 10 minutes without even being acknowledged (apparently the phone calls coming in were more important than a paying customer trying to pick up his food).
Erawan Thai is delicious  affordable  and probably one of my favorite lunch destinations.   Erawan is actually the first place I've tasted Thai cuisine. I've compared it to a handful of other restaurants in the neighborhood and still prefer it. Its kind of a monthly voyage to grab lunch here during work for me. I'd gladly walk across the walnut street bridge in the freezing cold to warm up with their three course lunch special. I prefer to eat in rather than bring it back to work with me  although its the same great taste without the relaxing atmosphere.  Erawan is a good choice  for grabbing a quick Thai lunch. I recommend the drunken noodles  they're totally my favorite.
I have mixed feeling about Erawan.   I like the food here very much.  I think the service has a good heart.  The problem on my last two visits (both Friday nights) is that there was only one waitress for the entire restaurant.  Our dinner took about 2 hours from start to finish.  Just hire more service and this could be a 4-5 star place.
I decided to check out Love & Honey after hearing that Questlove endorsed them. I grabbed my friend Myron who was visiting from out of town and we set off for Front Street. As a black woman whose family hails from the South  I'm genetically engineered to be skeptical of any fried chicken not prepared by someone's black grandmother or Aunt Johnnie Mae. I took a deep breath  crossed the threshold walked to the counter and placed my order. The chicken isn't prepared until you place your order so there's a bit of a wait. Fast forward to me digging into my box of chicken - this is actually good! The chicken was juicy and seasoned well. The skin was nice and crisp! The piece de resistance  however  was the cornbread with honey butter. It was damn good! Not slap yo mama good but when I see my mother this weekend we will have words. The only reason I'm giving 4 stars instead of 5 is because you can't choose all white or all dark meat. I detest chicken breast with every fiber of my being so this was almost a deal breaker for me. Luckily  Myron isn't picky about his chicken so he graciously traded his thigh for my breast. If you get the chance  do stop by  you'll be glad you did.
Chicken is done right - super crispy and delicious batter. Rivals the fried chicken at Lukoil (anyone who doesn't know  their chicken is out of sight  don't judge a book by its cover) Very friendly staff even though it was their hectic grand opening. A few cons - Mac and cheese was surprisingly lackluster. Go with pimento cheese spread instead. Also they ran out of cornbread which I'm chalking up to being a crazy grand opening.
I found the food very good here!  Yes  the chicken was fantastic  as was cornbread  shells and cheese and collard greens.  I also had the banana pudding  which was rich and creamy.  I also tried the sweet potato pie  which was also very good.  Both desserts had fresh whipped cream. Everything was homemade  fresh and tasty.  I hope they can maintain this high quality of food.
First time coming here! I got a 6-piece chicken with every side they offer (except the coleslaw). The food was absolutely amazing. I could not have asked for a more authentic dining experience. I ordered using Caviar with a $10 off voucher  but would have paid full price if I knew how amazing the food was. I recommend this if you are looking for homemade comfort food!   I've been using Caviar to get delivery from my favorite restaurants. Sign up with this link to get $10 off each of your next two orders in Philadelphia.: https://bnc.lt/W9Qc/c3aKuVuGyI
This food is life-changing. My wife works nearby and if I'm especially nice to her she'll grab me a 3 piece and cornbread. Also  the butter is more than likely fortified with narcotics because I'm most definitely addicted!
The fried chicken was amazing! Fried chicken is hard to get right (not too greasy  not over cooked  consistent crunchiness of the coating)... well  they nailed it. The mac and cheese was also delicious. The banana pudding was a huge surprise (figured - how good could it be?) - Uh-mazing. This came as a recommendation   so I glad I took it. The restaurant has a cute layout - geared a little more to take out  but there are seats available. No beer wine  but that may be a blessing given you won't have any room left!
I don't know where it all went wrong  maybe it was a bad batch but this chicken is not good. There's was no flakiness  and it was poorly seasoned. All I taste is the overwhelming flavor of celery seed and white pepper. Couldn't even eat the skin...very disappointed...drove all the way from Jersey
Just went there tonight with my wife for a nice dinner. The food was incredible! I had the NY STRIP and she had the lamb  and both were absolutely delicious and cooked perfectly. The service was also great  the waiter messed up a tiny bit our order so he got us 2 free dessert :) super nice! And if you have room for dessert  don't even think twice and order the fried oreos!
Yum  yum yummmmmmmmmmm. My man candy and I went to entree for restaurant week and both have a lovely evening.  For appe-tits (hehe) we got the balsamic calamari which was fresh and tart and fantastic. Came with a bunch of different sriracha sauces too which of course complemented the calamari perfectly. We also got the prosciutto wrapped dates stuffed with gorgonzola. Really rich and meaty in texture  and tasted amazing when you dipped it in their balsamic dipping sauce that came with the bread (oh yea  they give free bread and olive oil :) I found this to be a little on the rich side on it's own  but dip it in the sweet balsamic and it really changes things.  For dinner  I had the duck with a sun dried tomato and cherry sauce which came with purple potatoes and mushrooms. Mmm mmm  mmmm under the sun  I was a happy camper. The duck was crispy  tender  and perfectly cool while the sauce really complimented it perfectly. The potatoes were tender and soaked up the sauce really nicely.  Handsome pants had the chicken which is apparently the signature dish at entree. I don't know what it was spiced it but it had a morroccan flavor to it. Came with delicious mashed potatoes too.   For dessert we got the white chocolate creme brulee and the limencello cake. The limencello cake was lemon cake with cheese cake layering and the creme brulee was just delicious. Both were really great  but seriously could use a cup of coffee. Veryyyy decadent desserts after a heavy meal.   Our waitress was also really great! She recognized our needs and put up with our indecisiveness  but was not over bearing. Our table unfortunately was right in front of the door so we were a bit cold  but that did not affect my dining experience.  Definitely would go here again!

I am ... in Love.  Philly Love...that's what they call it?  This is the perfect cafe that has outside seating  without the hustle and bustle of cars driving by and wafting dust in your face.  You actually look into the park  rather than another old building.  This cafe serves a variety of organic coffees  wine (their house boxed...yes boxed..wine..is fantastic!)  cheeses  snacks  deli options and even a dinner setting.    If I had to choose to work remotely  I would choose this little knook.  Outside seating at Taluluas or indoors on their cocktail tables.    Must tries: Iced Coffee Cappuccino Cheese Board  Salami Deli options  Cookie (free from yelp checkin!) House white wine I hear you can order cocktails from Talula's garden  but I'm so happy w/ the offerings here.    The service is great and don't forget the coffee punch card!  Just the absolute perfect setting and likely more affordable pricing than Talula's Garden.
Many legitimate complaints about wait times and food sitting out and not freshly made....for the prices  I agree. Given that there's not much else near by to grab and go  I suppose they can up charge for the convenience and locally sourced foods.  I also think the service has been at least friendly and attentive if. It lightening quick. I'll give them a chance to work out the kinks.  I recommend that you at least come here  but come in the nice weather  on a weekend  and get yourself a nice spiked coffee....which you can't getting any other cafe that isn't a straight up bar...and then sit outside and look out over beautiful Washington Square Park. Try a pastry with it. If you're looking for daily lunch every day on your lunch break  well  you may have to wait for Talula to figure out that the coffee is the only thing you can afford to get here every day.
Delivery takes a good amount of time  but the pizza is completely worth it. Big slices of thin pizza perfect if you like to fold your slices.
My friends all go for pizza which doesn't appeal to me other than fun fact that a large is the size of a small planet. BUT what I did discover whrn I needed a very quick bite  was that their Italian combo is spectacular! Flavorful and fresh  and bonus if you add hot peppers on it!
I hadn't had Lazaro's since my undergraduate days and decided it was worth a trip back  now that I live about five blocks away.  It was Sunday night  and Lazaro's was sufficiently busy.  My gf and I ordered a large mushroom pizza and waited patiently in the seating area next door for our pie.  10 minutes.  20 minutes.  25 minutes I go check.  \Large mushroom?\"  It's next  it's next.  We did have a pizza a few minutes later  but for a pizza this thin  waiting 30 minutes was a little long.  And I didn't appreciate the comment from the guy when I went back to get a couple of forks and knives  \"next time you should order ahead  you know\".  Thanks  jerk.  I will now that I know it takes 30 minutes to make a really flat pizza.    The pizza itself - also about three stars.  The mushrooms were good  but they kind of skimped on the amount they gave.  The sauce is sweet and the crust nice and thin  just as I like it.  Anyway I'm sure I'll be back but I wish there was somewhere that stood out for me as damn good pizza."
After just moving to Philly  I was excited by the large number of well reviewed Pizza joints in the area.  We tried Lazaro's 1st as it was close to our house.   We got a large half cheese half pepperoni pie and an order of garlic knots. The garlic knots were pretty good. Less greasy than places I've ordered from in the past and definately not overdone on the garlic. The pizza was typical thin crust  but not as crispy as I would have liked. The sauce  however  was superb. It is much sweeter than any sauce I've had in the past and really had a nice zing to it. The peperoni wasn't crispy enough.   Pretty good pizza  but I think I can find better in Philly.
good tomato pie or well red pizza.   also good chicken finger sub (with honey lettuce and tomaeters)
Great pizza and better service  wish they would take cards tho  other than that  great business
i've ordered delivery from these guys a couple of times  whilst working. not only did i enjoy it  i enjoyed to the extent of OMGTHATSAGREATSAMMICH!!!!  seriously....i dig the zucchini sticks  all fried up  too.  (btw--the sammich of awesome is the veggie hoagie--eggplant  ahoy!)
I have been ordering from Lazaro's Pizzeria & Grill for years. I have never once been disappointed  and the delivery has always been very quick. Lazaro's is the only place in the city that I order pizza and cheese steaks from  definitely a great choice for any night  especially when the game is on. Thank you for the years of great food and service!
I think you should prepare yourself before entering. Get out your hankie  tie your hair back  and prepare to salivate. This is what happens when you enter the haven of Lazaros.   I have to admit to only trying their cheese and white pizza. The white pizza (classic) is what kills me. It kills me with sweet cheesy flavor. And then brings me back to life with the wafting scent of yet another gargantuan slice. You begin to sweat  dare I have another slice? Who is looking anyways? Is this a sin or can I get away with it?! All natural fears. Let me lay them to rest. Lazaros is awesome. It is best to stuff yourself with awesome so that you have awesome inside you. For the next few hours at least. Then you have to come back for more.   Which is EXACTLY what I plan to do this weekend. Me. Lazaros. It's the only kind of date I need to have the rest of my life!   Also  if you are complaining about the size of this food look at their name. Lazaros Pizza House. They had to get a HOUSE added for this kind of food. Because it feeds a house of people. Duh  don't hate  it's implied in the title foo!
I was excited to try a new place. I arrived to wait for an hour with no answers to when a table will be available. After pestering the hostess  she says we will reservations coming in  it will be another 30 minutes or so. So waiting an hour and not being able to get a drink or a table I left. I hope to try this place some day.
I enjoyed everything about Relish from Raisin in the Sun to the live band to the karaoke to the Hennessy Sangria to the seafood Mac n' Cheese to the Fried Catfish  greens  and sweet potato mash to the fact that my reservation was honored in spite of being about 30 minutes late in arriving to fellowshipping with the party next to us.   The only thing I hated was having to leave  but I plan to visit again real soon!
I hosted a birthday party for a loved one at Relish this past Saturday night. It was amazing! We had a party of 40+ including attendees from the age of 1 on up to 96. The birthday girl as well as every single guest in attendance had nothing but praise for Relish. The experience was just great from start to finish. I really appreciated the integrity  professionalism and patience that I experienced throughout the entire event. The establishment  event coordinator  Sherri Lee Stevens and all of the staff  food  ambiance  etc was just wonderful. We had a few mishaps come up on our end (overbooking  tardiness  etc)  however  the wonderful Relish staff was able to work everything out for us  with a smile! I really can't say enough nice things about the place. If I ever have to host another event in Philadelphia  I'll definitely book Relish again. I highly recommend it.
My husband and I came here for the first time on Friday 4 22 16. We had a 630 reservation. After our arrival we had about a 15 min wait before being seated in the bar club area. We were seated near the kitchen walkway( a high traffic area). I immediately requested from the host to be moved to the table rt next to me but was told it was reserved for 4 people even though a couple had just vacated it. Although a little disappointed about the seating we went ahead and ordered our dinner. My husband had the crab cake meal and i ordered the chicken meal. The portions were good  however the greens and fried chicken needed a little more seasoning. The entertainment with Cedric Napoleon tanqueray hayward and t webb was awesome. Our server Chai was also very attentive. We were disappointed that within 30 minutes of being seated they sat 2 people at the table next to us which previously they told us it was 4 people. I don't understand why we could not have been sat at that table to begin with. Disappointed that throughout the entire evening we kept getting bumped by waiters waitresses trying to serve others in this high traffic area. Overall rating lowered due to seating accommodations.
Celebrated my birthday at Relish.  The service was awesome from the time we entered the door until we left.  Food was great...Fried Chicken  Crab cakes  Short Ribs  Caribbean Chicken  Mac n Cheese  Collards.  Our waitress Kai (I think that's her name) was very attentive and patient.  The music was great....we had at great night and will definitely go back.
Y'all. Overrated is not even THEE word. I don't get the hype. I can't believe that my fellow Yelpers deceived me like this.  We came about 10-15 minutes before our reservation for Sunday brunch and was seated about 5 minutes after. So the wait time wasn't bad. Once we were seated we headed over to the buffet and personally speaking I've seen bigger buffets but at this point  I was trying not judge just yet. Took a stroll around the buffet  they had a bit of a variety of food: waffle  omelette and pasta stations  BBQ and fried chicken  fried fish  shrimp and grits  challah French toast  home fries  curry chicken salad  Caesar salad  fruit salad  small desserts  etc.   All that I stated above was practically majority of the buffet. I managed to get a pasta and omelette made to my liking with Caesar salad  fruit  turkey bacon  curry chicken salad and fried fish. Y'ALL! The best thing on my plate was that fried fish and that's probably cause I added hot sauce to it. The rest of the food was... meh. I can't believe I was in a soul food place where the food was not seasoned. The only reason why they are getting two stars is one because of the wait time and the other because the waitress was nice. But it even took long for her to come around at times. Also  the drinks weren't bad. It could be good for a happy hour but as a person who goes to many brunches and places to eat in the tristate area  I was disappointed in the quality of the food. The food was overpriced. Those who gave 4 or 5 stars truly hasn't been to a good brunch.
This used to be one of my favorite restaurant in the city  however the service and food have gone by the wayside! It's almost as if they don't even care or think that it's alright to serve you food that is not cooked thoroughly. Save your time and Money!!!!!
Excellent Food! Excellent Service! I frequent this place. It's my favorite restaurant in the area. Love the cornbread ( I bought 12 pans for my engagement party). The shrimp and grits dish is amazing.   Entertainment is around $6 a set and can range from eclectic jazz (which I'm not a fan of) to traditional jazz. If your not into the music you can always eat it the main dining room and save your money.   If you would like to experience an assortment of what Relish has to offer  try their Sunday Brunch. Visit www.relishphiladelphia.com
I've been wanting to try this place for awhile. People rave about it. I actually haven't gotten a chance to go to the actual restaurant ... But I decided to try UberEATS and Relish was one of the restaurant choices  so I figured why not? I ordered cast iron fried buttermilk chicken and it came with Mac and cheese and collard greens. The chicken arrived crispy and was pretty tasty (not over seasoned!) the Mac n cheese was good  but the noodles were a bit over cooked. The collards were bland... Def could use some seasoning. Maybe my expectations were too high  the food was good don't get me wrong but I've had better soul food. I will try again  but plan to dine in next time!
Wanted to find a good option for Southern cuisine and was referred to this place. Decided to surprise my hubby on his 55th birthday. We came on a Sunday so we had the buffet which included a full salad bar. Favorites would be the biscuits  cheese grits  Mac n cheese sautéed cabbage. Everything was good but those were my standouts. The fried fish was nice as well as fried chicken. The service was excellent  the ambience was very nice and the music was great!!  Would definitely make the drive from Jersey again!!
I went over to Jake's one day during my lunch break from work  as I had been eager to try that place out for over a year now!  Before I entered  I scanned the menu posted outside the shop  and decided to go try myself a cheesesteak.  I ordered the Steak and Egg  cheesesteak with American cheese and ketchup topped with an egg sunny-side up.  While the sandwich was listed as having sriracha ketchup on it  I'm not a fan of the hot and spicy side of things  so when I asked if I could substitute regular ketchup for the sriracha  the counter girl gladly obliged.  I also ordered a small side of fries to accompany my cheesesteak.  While I waited for my order to be ready  I noticed that at each table in the shop  there is a roll of paper towels--and I can totally understand why.....so delicious yet so messy!! I also notice that they have what they call a \5 Pound Challenge\"--in which participants are challenged to polish off 5 pounds of food (a 2-foot long cheesesteak  4 Philly soft pretzels  a box of Tastykakes  24 Peanut Chews  and a Cherry soda)  and if they have done so in 45 minutes or less  it's ALL free!  I could never eat that all on my own  but would love to split that with a few people!  Definitely a great idea for friends!  Can't wait to try more of their menu items including their milkshakes AND the chocolate covered bacon!"
I had the steak and egg  really good. Excited to go back and try the Village Turkey and the Barnyard.
I really like the Schmeer.  I mean  really really like it.  It's just a delicious combination of tender turkey breast  provolone  spinach  sliced RED onions  roasted peppers  and a garlicky mayo on a soft  fresh yet crusty roll.  A whole sandwich will easily be enough for 2 meals.  I brought half for lunch and it was still delicious after spending a day and a half in the refrigerator  although I would recommend eating it fresh.  Dad's pick is the midtown chicken (he's trying to be healthier)  which still tastes pretty darn good and indulgent with sliced  grilled chicken  avocado spread  peppers  onions  and a mix of cheddar and mozzarella  in a salad bowl.  While I'm a bread-loving gal  the salad and bowl options are nice if you want something flavorful yet low carb.  Apparently you can also get a sandwich over fries instead of a roll if you really are looking for a heart attack.  One of these days I will work up the gusto to try that.  In the meantime  I am very much content with the sandwich options here and even more grateful to my wonderful  foodie father who actually drives down to the city just to grab a few for lunch and dinner (and bring some extras for my lunch the next day).  Definitely worth a visit if you're in Philly and want a quick  satisfying  flavorful  and affordable bite.
I I'm in town from Arizona and my wife saw this place on tv and told me I had to go. Absolutely worth it. Ordered the garlic bomb off their \secret\" menu and it did not disappoint. Well worth the trip and the service was great. They were helpful  friendly  attentive and expedient."
Thank you Jake's for bringing something different to the table. The Market East options in the sandwich department tend to mirror each other so it is great to have some variety in a menu.   These sandwiches are true sandwich lover sandwiches. Great bread with fresh ingredients. I have eaten lunch in twice and the workers are very friendly and make it a casual environment. They probably eat for free all day back there so I would be a happy camper too. I have tried the Barnyard  Mensch and the Italian all of which make a great and filling lunch. All the sandwiches are $7 or $8 which isn't too bad with the quality of the products.   My only true complaint is the fries. They are pretty boring on their own and not crispy enough. I will be back soon to continue my quest to try every sandwich on the menu  minus the leaner ones section  no time for that.
I am sad to report I have not been nearly as happy as I had been in the past. Things were not put together with care  and the meat has been dry my past couple trips. Still good  but down a peg.
I love the garlic bomb and the pulled pork sandwich. When I lived in the Market East neighborhood  I used to visit Jake's at least once a week. The $5 pork sandwich special on Monday was very good for my grad student wallet---and very good for my tummy. Fries with special sauce on the side is a must. And the meal completes with a cup of birch beer that cools me down before another wild bite of sandwich.
I had the Cowboy. Very tender shredded pork with grilled onions.  Amazing!  Good quality  good value.  It is also a good vibe.  I met the owner  and you can tell he's passionate about his concept.
The pig sandwich is awesome and very reasonably priced  I try to stop here at least once a week for my pork fix. Prior to trying Jake's pig  I felt that no pork sanwich in the city could live up to the GOAT of pork from the little shack on Synder Ave.  Well  I still feel that no pork sandwich is better but Jake's is pretty close  and its not always easy to go to the little shack on Snyder but Jakes is right on the corner of where I work.  Go get the pig on a Monday and experience reverse sticker shock  they have a monday special on the pig that makes me feel like I am robbing from them.
Really nice addition to the 'hood.  Sandwiches are served on Carangi rolls  seeded  unseeded or multigrain.  The Midtown Chicken was great  red onions  cheddar and a red pepper spread went down fast.  The Village Turkey was not as good - the meat was good but the roll kind of overwhelmed the sandwich.  Fries were hot  crispy and above average.  Sodas are \micro-brewed\".  I'll definitely come back - all the ingredients were fresh and good  and it's the next best thing to a Paesano's without the real thing."
Good food--loved the gnocchi with marinara the baked eggplant appetizer was very good too  The service was very slow  but despite this  I'd go back  the food is just that good
Excellent food atmosphere and service . Everything was fresh and hot when we were served  and the dessert tray is absolutely amazing!  We walked here from our hotel ( Hotel Monaco) and are so glad we did! Bon Appetito!!
My boyfriend and I have visited here a bunch of times and we will still be coming here! Everything has always been great! Mussels are amazing in the white and the red! Chicken Marsala is amazing! The drinks are a little to expensive  some of them being as much as your meal itself  but I guess that's because the location. Grab a drink across the street at Las Vegas lounge first to pay average price for a drink than head to an amazing dinner here!
Its a decent place. Not the best italian food I had  but it was good. I was here for restaurant week. I had the lobster ravioli  the meatball appetizer and the brownie dessert. It was all good  nothing stood out as the best thing I have eaten. It was pricey  but I wasn't disappointed. They have a good wine list to choose from. Overall  if you are in the area I would give it a try. Its not something I would trek a long way down to eat.

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [15]:
#Split train test for testing the model later
vld_size=0.15
X_train, X_valid, y_train, y_valid = train_test_split(reviews_df['Reviews'], yelp_reviews_df['Business_Id'], test_size = vld_size)

# Create two tables of user, text and bussiness

In [16]:
reviews_df['Business_Id'].count()

8303

In [17]:
newreviews_df = reviews_df[reviews_df['Business_Id'].isin(restaurants_df["Business_Id"])]
newreviews_df['Business_Id'].count()

415

In [18]:
newreviews_df.head(25)

,Business_Id,User_Id,Rating,Reviews
391,ZKPrXH_GNW_AtZ31tP3NmA,uIHI_BzJcNMxFAZA5bYeXg,4.0,Recently visited dinner daughter visiting Univ...
392,ZKPrXH_GNW_AtZ31tP3NmA,s9FrHlk9kPnfSAdAgKNtWA,4.0,love place 2 reasons 1 husband proposed 2 amaz...
393,ZKPrXH_GNW_AtZ31tP3NmA,eFXy9H9H2tBfnyNahNUUEQ,4.0,Gotta love White Dog food service reliably goo...
394,ZKPrXH_GNW_AtZ31tP3NmA,ETyduRMWNWg7cjoZaRxmaQ,4.0,got chicken sandwich broccoli rabe side salad ...
395,ZKPrXH_GNW_AtZ31tP3NmA,zCDU0cm2K_R7HozWqTgm0w,4.0,Mold hot dog ordered mold bun Im paying 750 ho...
397,ZKPrXH_GNW_AtZ31tP3NmA,d2SmmiFbMXUxT5-cTzu0OQ,4.0,happened White Dog Cafe First time friend Dans...
398,ZKPrXH_GNW_AtZ31tP3NmA,nBdv5Br4G8pDWXXqSXhUug,4.0,Hello Last night wonderful meal tuna tartar du...
399,ZKPrXH_GNW_AtZ31tP3NmA,T9aisv9FFuEbO9hSgi-efw,4.0,wonderful little spot University City offers c...
611,kVTHnhgYUw-Pmr7wgDB4_g,uIMcOM39MNJfkEFVDWu2-A,3.5,Seating horrible came without reservation half...
612,kVTHnhgYUw-Pmr7wgDB4_g,YnbiDyzD3NpBTxeMQdtzDA,3.5,heard great things Distrito dying go Overall g...
613,kVTHnhgYUw-Pmr7wgDB4_g,7QvDBjYGPyITqTWiO02aaw,3.5,honest expected little place completely put ga...
614,kVTHnhgYUw-Pmr7wgDB4_g,GEaaJ2U52FO5I8xXpp0Q1Q,3.5,would really love say liked place cant questio...
615,kVTHnhgYUw-Pmr7wgDB4_g,b62H4NDrvOEV5D_eEoJpww,3.5,Got chance finally try Distrito part Universit...
616,kVTHnhgYUw-Pmr7wgDB4_g,DHEGr6NhuUmh8BIgqBrwxg,3.5,Sorry think place suffers University City grad...
617,kVTHnhgYUw-Pmr7wgDB4_g,MdUimpfJQHijcy1DZu-r4A,3.5,expecting traditional Taco joint menu go elsew...
618,kVTHnhgYUw-Pmr7wgDB4_g,b2zb8N_so3WKNFhYkoB9YA,3.5,food great special treatment lot standard mexi...
619,kVTHnhgYUw-Pmr7wgDB4_g,mTnlujPxGhxwlyPL4oXzrQ,3.5,Debated whether give 4 5 stars finally convinc...
880,6ewV-e7-39oqYUq3yZuIyw,7RuSAc-Mslk4aizXXJpQTg,4.0,Oh Sabrina losing touch last experience partic...
881,6ewV-e7-39oqYUq3yZuIyw,ktk1ADOeTUgAjE_Y5bvtqQ,4.0,Three friends came New Years day brunch used W...
882,6ewV-e7-39oqYUq3yZuIyw,dzy9FhzyfGcfENgY8HJ7Dg,4.0,Amazing Huge huge portions Went brunch sat bar...
883,6ewV-e7-39oqYUq3yZuIyw,CVzp4BJBs1NAbQ8rngJWuw,4.0,Parking hard find towner onstreet Sabrinas eas...
884,6ewV-e7-39oqYUq3yZuIyw,Tu4ATXLhy8kRTjpQCnl2pA,4.0,love place think might obsessed place take vis...
886,6ewV-e7-39oqYUq3yZuIyw,tLS3jsruzp9Y1R_UyUG6QA,4.0,Amazing food fabulous service affordable price...
887,6ewV-e7-39oqYUq3yZuIyw,c_NLNsE900icl8Kmsgh8GQ,4.0,biggest issue Sabrinas blandness food positive...
970,3gVSrS4kffGGZT8oXHsIcw,iX1msXXgIPXTa6vZ6izCZQ,3.5,Came friends University City Dining Days great...

In [19]:
userid_df = newreviews_df[['User_Id','Reviews']]
business_df = newreviews_df[['Business_Id', 'Reviews']]

In [20]:
userid_df.head()

                    User_Id                                            Reviews
391  uIHI_BzJcNMxFAZA5bYeXg  Recently visited dinner daughter visiting Univ...
392  s9FrHlk9kPnfSAdAgKNtWA  love place 2 reasons 1 husband proposed 2 amaz...
393  eFXy9H9H2tBfnyNahNUUEQ  Gotta love White Dog food service reliably goo...
394  ETyduRMWNWg7cjoZaRxmaQ  got chicken sandwich broccoli rabe side salad ...
395  zCDU0cm2K_R7HozWqTgm0w  Mold hot dog ordered mold bun Im paying 750 ho...

In [21]:
business_df.head()

                Business_Id                                            Reviews
391  ZKPrXH_GNW_AtZ31tP3NmA  Recently visited dinner daughter visiting Univ...
392  ZKPrXH_GNW_AtZ31tP3NmA  love place 2 reasons 1 husband proposed 2 amaz...
393  ZKPrXH_GNW_AtZ31tP3NmA  Gotta love White Dog food service reliably goo...
394  ZKPrXH_GNW_AtZ31tP3NmA  got chicken sandwich broccoli rabe side salad ...
395  ZKPrXH_GNW_AtZ31tP3NmA  Mold hot dog ordered mold bun Im paying 750 ho...

In [22]:
userid_df = userid_df.groupby('User_Id').agg({'Reviews': ' '.join})
business_df = business_df.groupby('Business_Id').agg({'Reviews': ' '.join})

In [23]:
userid_df.head()

                                                                  Reviews
User_Id
-5QrmUZTvniwryx3l3JM8g  favorite trendy ramen spot comfortable atmosph...
02EPgkmrh39Dr7uXc1bqTQ  Food excellent cheap quality quantity waitress...
0DB3Irpf_ETVXu_Ou9vPow  used live right next Desi Chaat House pretty m...
0YmEeQEzqwMwuWKvf3PTNA  got Philly STARVING Yelp place eat Tacos Memo ...
0dcknuP3VLaO_Q6ugNmLQA  eat coin aint cheap business better believe fa...

# User Tfidf Vectorizer with 5000 Features (represent 88% of all words)

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [25]:
#userid vectorizer
userid_vectorizer = TfidfVectorizer(tokenizer = WordPunctTokenizer().tokenize, max_features=5000)
userid_vectors = userid_vectorizer.fit_transform(userid_df['Reviews'])
userid_vectors.shape

(387, 4786)

In [26]:
userid_vectors

<387x4786 sparse matrix of type '<class 'numpy.float64'>'
	with 19738 stored elements in Compressed Sparse Row format>

In [27]:
#Business id vectorizer
businessid_vectorizer = TfidfVectorizer(tokenizer = WordPunctTokenizer().tokenize, max_features=5000)
businessid_vectors = businessid_vectorizer.fit_transform(business_df['Reviews'])
businessid_vectors.shape

(50, 4786)

# Matrix Factorization

In [28]:
userid_rating_matrix = pd.pivot_table(newreviews_df, values='Rating', index=['User_Id'], columns=['Business_Id'])
userid_rating_matrix.shape

(387, 50)

In [29]:
userid_rating_matrix.head()

Business_Id,-5Rah4ZvWsDu4oilUZxhtw,14ZGwnDyydXdSBsLXpSUrA,3gVSrS4kffGGZT8oXHsIcw,41LEg4ZgFDVnZfToxGXiGA,5ICrDkwtX4ykKOLVJ1tFJA,6GXMHrB8u-3nq87zE1Av0w,6_LnAQQ0-mml8YgpfRjGuA,6ewV-e7-39oqYUq3yZuIyw,8yGZhBwFFLtOVLY9Do8ohQ,99e7bysta1myyrQogFEWUQ,...,lS42krxXMm-HIk7dntRsKQ,pgri9CUZXGy9hi6UMMQR6A,qtyNbCXut-RQnnEQNJ9UzA,s2JiYzE7i68cXIV6YEcVTw,uB12vX5p9T8z0g2Eq3bBBQ,uE40984_YDgVvPeRpFcCaQ,uvj_tGQrGDSVXjNU4pHjCA,yG5tkMER9Ftkv4RDwMaQuA,zU5PPd9j4bYC_MepNSEDcA,ziyXteCmNmRprs10buP2iQ
User_Id,,,,,,,,,,,,,,,,,,,,,
-5QrmUZTvniwryx3l3JM8g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02EPgkmrh39Dr7uXc1bqTQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
0DB3Irpf_ETVXu_Ou9vPow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0YmEeQEzqwMwuWKvf3PTNA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0dcknuP3VLaO_Q6ugNmLQA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
P = pd.DataFrame(userid_vectors.toarray(), index=userid_df.index, columns=userid_vectorizer.get_feature_names())
Q = pd.DataFrame(businessid_vectors.toarray(), index=business_df.index, columns=businessid_vectorizer.get_feature_names())

In [31]:
Q.head()

,0,030503062010,04,05,08,09,1,10,100,1012,...,étaient,、,。,不喜欢的人会很不喜欢,可以提前跟店家说一下不要加,唯一的缺憾是冰粉上面会加橙皮以及其他一些类似五仁的材料,红油,食物非常正宗,麻酱和红糖用得都很正,，
Business_Id,,,,,,,,,,,,,,,,,,,,,
-5Rah4ZvWsDu4oilUZxhtw,0.0,0.0,0.000000,0.037209,0.000000,0.0,0.0,0.02148,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14ZGwnDyydXdSBsLXpSUrA,0.0,0.0,0.058513,0.000000,0.058513,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3gVSrS4kffGGZT8oXHsIcw,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41LEg4ZgFDVnZfToxGXiGA,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5ICrDkwtX4ykKOLVJ1tFJA,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Gradient Decent Optimization

In [32]:
def matrix_factorization(R, P, Q, steps=25, gamma=0.001,lamda=0.02):
    for step in range(steps):
        for i in R.index:
            for j in R.columns:
                if R.loc[i,j]>0:
                    eij=R.loc[i,j]-np.dot(P.loc[i],Q.loc[j])
                    P.loc[i]=P.loc[i]+gamma*(eij*Q.loc[j]-lamda*P.loc[i])
                    Q.loc[j]=Q.loc[j]+gamma*(eij*P.loc[i]-lamda*Q.loc[j])
        e=0
        for i in R.index:
            for j in R.columns:
                if R.loc[i,j]>0:
                    e= e + pow(R.loc[i,j]-np.dot(P.loc[i],Q.loc[j]),2)+lamda*(pow(np.linalg.norm(P.loc[i]),2)+pow(np.linalg.norm(Q.loc[j]),2))
        if e<0.001:
            break
        
    return P,Q

In [33]:
%%time
P, Q = matrix_factorization(userid_rating_matrix, P, Q, steps=25, gamma=0.001,lamda=0.02)

CPU times: user 1min 20s, sys: 5.05 s, total: 1min 25s
Wall time: 30.2 s

In [34]:
Q.head()

,0,030503062010,04,05,08,09,1,10,100,1012,...,étaient,、,。,不喜欢的人会很不喜欢,可以提前跟店家说一下不要加,唯一的缺憾是冰粉上面会加橙皮以及其他一些类似五仁的材料,红油,食物非常正宗,麻酱和红糖用得都很正,，
Business_Id,,,,,,,,,,,,,,,,,,,,,
-5Rah4ZvWsDu4oilUZxhtw,0.000000e+00,0.000000e+00,0.000000e+00,0.042769,0.000000e+00,0.0,0.000000e+00,3.229334e-02,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14ZGwnDyydXdSBsLXpSUrA,9.174749e-12,5.411205e-08,9.292148e-02,0.000000,9.292148e-02,0.0,8.811944e-12,6.898484e-03,1.308731e-15,1.359473e-11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3gVSrS4kffGGZT8oXHsIcw,6.377822e-08,4.802993e-08,2.348853e-11,0.000000,2.348853e-11,0.0,6.203674e-08,9.758189e-08,1.688802e-11,9.468977e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41LEg4ZgFDVnZfToxGXiGA,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5ICrDkwtX4ykKOLVJ1tFJA,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,3.342382e-04,5.173488e-03,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
# Here we can view the principal words that are mentioned about the restaurant.
Q.iloc[7].sort_values(ascending=False).head(10)

brunch       0.241662
toast        0.211703
eggs         0.183513
french       0.176270
fries        0.174674
challah      0.174463
app          0.173930
olives       0.170844
pineapple    0.170172
came         0.161119
Name: 6ewV-e7-39oqYUq3yZuIyw, dtype: float64

In [36]:
# Store P, Q and vectorizer in pickle file
import pickle
output = open('yelp_recommendation_model_8.pkl', 'wb')
pickle.dump(P,output)
pickle.dump(Q,output)
pickle.dump(userid_vectorizer,output)
output.close()

# Run prediction according User's preference

In [41]:
words = "burger fries"
test_df= pd.DataFrame([words], columns=['Reviews'])
test_df['Reviews'] = test_df['Reviews'].apply(text_process)
test_vectors = userid_vectorizer.transform(test_df['Reviews'])
test_v_df = pd.DataFrame(test_vectors.toarray(), index=test_df.index, columns=userid_vectorizer.get_feature_names())

predictItemRating=pd.DataFrame(np.dot(test_v_df.loc[0],Q.T),index=Q.index,columns=['Rating'])
foundRestaurants=pd.DataFrame.sort_values(predictItemRating,['Rating'],ascending=[0])[:7]

for i in foundRestaurants.index:
    name = restaurants_df[restaurants_df['Business_Id']==i]['name'].iloc[0]
    categories =restaurants_df[restaurants_df['Business_Id']==i]['categories'].iloc[0]
    latitude = restaurants_df[restaurants_df['Business_Id']==i]['latitude'].iloc[0]
    longitude = restaurants_df[restaurants_df['Business_Id']==i]['longitude'].iloc[0]
    rating = str(restaurants_df[restaurants_df['Business_Id']==i]['stars_business'].iloc[0])
    topRecommendations = pd.DataFrame({
        "Name": [name],
        "Categorie": [categories],
        "Latitude": [latitude],
        "Longitude": [longitude],
        "Rating": [rating]
    })

    print(restaurants_df[restaurants_df['Business_Id']==i]['name'].iloc[0])
    print(restaurants_df[restaurants_df['Business_Id']==i]['categories'].iloc[0])
    print(restaurants_df[restaurants_df['Business_Id']==i]['latitude'].iloc[0])
    print(restaurants_df[restaurants_df['Business_Id']==i]['longitude'].iloc[0])
    print(str(restaurants_df[restaurants_df['Business_Id']==i]['stars_business'].iloc[0])+ ' ' +str(restaurants_df[restaurants_df['Business_Id']==i]['review_count'].iloc[0]))
    
    print('')

#topRecommendations.head()

burger fries
Bobby's Burger Palace
Sandwiches, American (Traditional), Burgers, Restaurants, Salad
39.954086811
-75.2009592271
3.5 788

Lee's Deli
Sandwiches, Burgers, Delis, Restaurants, Local Flavor
39.9484414
-75.2171163
4.5 175

HipCityVeg - University City
Sandwiches, Food, Burgers, Restaurants, Vegan, Desserts
39.953549
-75.202991
4.0 314

New Deck Tavern
Irish, Gastropubs, Pubs, American (Traditional), Nightlife, Bars, Restaurants
39.9535171
-75.1926364399
3.5 419

Sabrina's Café
Breakfast & Brunch, Restaurants, Vegetarian, American (New), American (Traditional), Comfort Food, Cafes
39.9598792
-75.1906815
4.0 833

Hummus Grill
Specialty Food, Food, Sandwiches, Middle Eastern, Vegetarian, Ethnic Food, Restaurants, Mediterranean, Greek, Salad
39.954349
-75.2021586
4.0 372

Renata's Kitchen
Breakfast & Brunch, Caterers, Tapas/Small Plates, Event Planning & Services, Middle Eastern, Mediterranean, Restaurants, Greek
39.9496602
-75.2026672
4.0 203

In [38]:
px.set_mapbox_access_token(MAPBOX_API_KEY)
fig = px.scatter_mapbox(topRecommendations, lat="Latitude", 
                  lon="Longitude", color="Rating", hover_name="Name", size_max=30, zoom= 13, width=1200, height=800)

In [39]:
px.set_mapbox_access_token(MAPBOX_API_KEY)
px.scatter_mapbox(topRecommendations, lat="Latitude", 
                  lon="Longitude", color="Rating",hover_data=["Name","Latitude","Longitude"],  zoom= 10, width=1200, height=800)